### ISSUE TITLE
How are token hashes generated and what invalidates them?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [r-lib/gargle#100]
May I ask how the hashes are generated for stored tokens?  Upon upgrade to latest CRAN version all the current hashes invalidated, which broke tests etc. so would like to see if this was a one off event for this version update, or something to control for.

e.g. When I do `gargle_oauth_sitrep()` for tokens generated with `gargle_0.3.0.9000` they are now invalid under `gargle_0.3.1.9000`

```r
> gargle::gargle_oauth_sitrep()
gargle OAuth cache path:
/Users/mark/.R/gargle/gargle-oauth

Error: Cache contains tokens with names that do not match their hash:
  * Token stored as '1b8940c7aac648dbaeXXX_me@XXX.me'
        but hash is '15a83712935cd4cced6eXXX_me@XXX.me'
  * Token stored as '4521787cbfb2c71b4ecXXX_me@XXX.me'
        but hash is '3189ce145ca913171118XXX_me@XXX.me'
```

I would like the hashes to remain as constant as reasonably possible.

**Comment by jennybc** [comment]
Here's the `$hash()` method for `Gargle2.0` objects:

https://github.com/r-lib/gargle/blob/cc987c09c37d740cfc5a5c61e79fae4edb3a5cde/R/Gargle-class.R#L143-L145

I.e. it just adds the email to the `Token2.0` hash.

Here's the `$hash()` method for `Token2.0` objects:

https://github.com/r-lib/httr/blob/69ee0a1ae541bba03b4301ee1e9e79637805351a/R/oauth-token.r#L100-L111

``` r
hash = function() {
    # endpoint = which site
    # app = client identification
    # params = scope
    msg <- serialize(
      list(self$endpoint, self$app, normalize_scopes(self$params$scope)),
      NULL
    )

    # for compatibility with digest::digest()
    paste(openssl::md5(msg[-(1:14)]), collapse = "")
  }
```

So the hash will change if anything about the endpoint changes or app or scopes. And, I suppose, there is also the chance for openssl's md5 method to be part of the story, though seems unlikely.

**Comment by jennybc** [comment]
Are you using cached OAuth2 tokens in tests? That seems like something I would avoid, but maybe I don't understand or share your use case.

**Comment by MarkEdmondson1234** [comment]
> So the hash will change if anything about the endpoint changes or app or scopes.
Hmm I don't know why these caches are changing then, as those should be all the same.  

I have cached OAuth2 tokens for backward compatibility tests.

**Comment by jennybc** [comment]
You can load these tokens up "easily", since they are just stored one token per `.rds` file and dig around a little, to get some visibility into what's gone wrong.

I did this to myself once during gargle development, but now I can't remember exactly what lead to it.
