### ISSUE TITLE
Improve docs for deployed environments

### ISSUE THREAD

**Issue by jennybc** [r-lib/gargle#104]
This is a case of me opening an issue retroactively.

@akgold @andrie @jimhester 

I'd appreciate your 👀 and opinion, most especially on this section of the gargle article on non-interactive auth:

https://gargle.r-lib.org/articles/non-interactive-auth.html#arrange-for-an-oauth-token-to-be-discovered

My intention is to create the One Definitive Place to send people with these questions and to have a very clean concrete story.

Are we good?

**Comment by jennybc** [comment]
Maybe gargle should consider the option `httr_oob_default`? If someone has bothered to set that, it seems a better fallback than `FALSE`.

**Comment by akgold** [comment]
I think this is awesome. 

One little comment...feel free to disregard if doesn't fit well.

I feel like this could use a little more motivation at the top. Think it's definitely worth pointing out that you'll need to consider if you're even just knitting `.Rmd`. Easy to develop an `.Rmd` using interactive workflow and then start cursing when trying to knit and realizing workflow needs changing. Would also move content from "A Word about Deployed Environments" to top.

**Comment by jennybc** [comment]
Feedback is still welcome, but I'm happy with this doc at this point.
