### ISSUE TITLE
Better out-of-band auth docs

### ISSUE THREAD

**Issue by jennybc** [r-lib/gargle#105]
This is a case of me opening an issue retroactively.

@akgold @andrie @jimhester @nwstephens

I'd appreciate your 👀 and opinion on a new gargle vignette about out-of-band auth:

https://gargle.r-lib.org/articles/auth-from-web.html

My intention is to create the One Definitive Place to send people with these questions and to have a very clean concrete story.

Are we good?

This is somehow motivated by the impending release of googledrive and gmailr. Literally I am closing googledrive issues because of this. But it's easy to update the gargle website, so this is a case where we can make progress on documentation w/o formally releasing something. My hope is that client packages can delegate everything like this back to gargle (in terms of functionality and docs).

**Comment by jimhester** [comment]
I think it looks good to me

**Comment by akgold** [comment]
This looks great. 

Would probably advocate adding a little section here on using RStudio Team (i.e. RStudio Server + Deployment) and pointing people to the article from #104.

**Comment by jennybc** [comment]
@akgold Will you make your suggestions as a PR then?

We don't want it to become too RStudio-specific. But I also want to be realistic and clear ... so when/if our platforms really are the main examples, I'm happy to say so.

**Comment by jennybc** [comment]
Feedback is still welcome, but I'm happy with this doc at this point.
