### ISSUE TITLE
Adding a shinyapps.io verified clientId app?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [r-lib/gargle#108]
I've been looking at migrating Shiny auth via a JavaScript login button to `gargle` but a recent change in Google policy hits a snag.

They are now enforcing that the client id project must be verified before it will allow requests for authentication from there, and that can only be done if you own the domain.  This means that attempting to do Google auth for apps hosted on shinyapps.io now (or will soon) get a scary "This app is not authorised" screen.  Details [here](https://support.google.com/cloud/answer/7454865?hl=en-GB) It covers many APIs including Google Analytics, Google Drive etc.

For example, I have these JavaScript redirects setup for demo apps on shinyapps.io

<img width="629" alt="Screenshot 2019-08-18 at 13 34 36" src="https://user-images.githubusercontent.com/3155884/63223957-a1db6300-c1bd-11e9-98d6-e696382824e9.png">

Normally I'd just have to live with it, but the timing of `gargle` etc. seems fortuitous in that perhaps you could include a client.id/secret for a shinyapps.io authorised domain in `gargle` since RStudio is the owner.

**Comment by jennybc** [comment]
I'm not sure if it would work. I was the one who recently drove the verification process for the GCP Project that owns OAuth creds used in bigrquery and googledrive (and googlesheets4, when that releases). It's a fairly involved process, with a very uncertain outcome. You definitely have to spell out which APIs and scopes you will be using and why and have a clear [Privacy Policy](https://www.tidyverse.org/google_privacy_policy/).

It doesn't feel like shinyapps.io would be able to write down, in general, all of that stuff for apps hosted there.

Thoughts?

**Comment by MarkEdmondson1234** [comment]
Its a bummer if suddenly this all stops working, the solution for online auth will be to only host Shiny on domains you control.  But there may be another route, if shinyapps.io gets recognised as a “popular platform”: https://support.google.com/cloud/answer/7454865?hl=en-GB

Am pursuing that and hopefully that will fix it.

**Comment by jennybc** [comment]
> But there may be another route, if shinyapps.io gets recognised as a “popular platform”

Interesting! We would certainly be interested in helping to make that case. We ended up talking to interested parties internal to Google during the verification effort. So let me know if there's anything we can do.
