### ISSUE TITLE
Auth from Docker, using a service account, throws Bad Request (HTTP 400)

### ISSUE THREAD

**Issue by rensa** [r-lib/gargle#111]
I'm trying to package my Shiny app up in a Docker container and use a service account, rather than relying on the OAuth dance for my users. If I point my local R/gargle/googledrive setup to the service account, it appears to work fine. But if I put it in the Docker container, I get:

```
trying token_fetch()
trying credentials_service_account()
adding 'userinfo.email' scope
Error: Bad Request (HTTP 400).
trying credentials_app_default()
trying credentials_gce()
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
attempt from: googledrive
adding 'userinfo.email' scope
loading token from the cache
no matching token in the cache
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Please point your browser to the following url:
```

Here's the code I'm using to auth:

```r
options(gargle_quiet = FALSE)
  message(
    'Starting auth with service key @ ',
    mypackage:::app_globals$service_key)
    
  drive_auth(
    path = mypackage:::app_globals$service_key,
    scopes = c(
      'https://www.googleapis.com/auth/drive',
      'https://www.googleapis.com/auth/spreadsheets'))

  message('Auth done; looking up request sheets')
  drive_ls(ids$requests, team_drive = ids$drive) %>%
    filter(id != ids$template)
```

I'm not sure if the Bad Request error means that I'm getting the scopes wrong (although I haven't had a problem with them locally) or something else. I'm verifying when my package starts up that the file at the specified path actually exists, and I'm verifying when I run this auth function that the path is still correctly specified.

My DESCRIPTION (for the purposes of checking package versions) has: 

```
Remotes:
    tidyverse/googlesheets4@094063e,
    tidyverse/googledrive@3005625
```

**Comment by jennybc** [comment]
Can you run that code interactively in the Docker container? I.e. not necessarily inside a running Shiny app.

Does the app run locally, i.e. not inside the Docker container?

I'm not sure what's going on ...

Could it have something to do with a different port landscape in the Shiny app, running inside the Docker container? Try something like `httr::with_verbose(googledrive::drive_auth())` to get more detail on what's happening.

Why not use CRAN googledrive? What version does this SHA represent?

**Comment by rensa** [comment]
Thanks @jennybc, I'll have a crack at getting into the container interactively to get some more detail today. I wondered if it was something to do with the different network environment in the container.

(The SHA ("Use CRAN gargle") is from July 4. I'm just learning to move the MRAN snapshot date on my Docker container forward, so I'm hoping to switch to the CRAN release!)

**Comment by rensa** [comment]
Here's what I got (I've redcated the end of the body of the `grant_type` statement because I'm not sure whether I'd be leaking anything bad by posting it, but let me know if it would be helpful!)

```
> httr::with_verbose(drive_auth(path = '/credentials/hub-gargle-service-key.json'))                                                                                                                                                  -> POST /token HTTP/1.1
-> Host: oauth2.googleapis.com
-> User-Agent: libcurl/7.52.1 r-curl/3.3 httr/1.4.0
-> Accept-Encoding: gzip, deflate
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Type: application/x-www-form-urlencoded
-> Content-Length: 795
->
>> grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=[REDCATED]

<- HTTP/2 400
<- content-type: application/json; charset=utf-8
<- vary: Origin
<- vary: X-Origin
<- vary: Referer
<- content-encoding: gzip
<- date: Wed, 02 Oct 2019 01:33:21 GMT
<- server: scaffolding on HTTPServer2
<- cache-control: private
<- content-length: 201
<- x-xss-protection: 0
<- x-frame-options: SAMEORIGIN
<- x-content-type-options: nosniff
<- alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
<-
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
```

**Comment by rensa** [comment]
So, trying to get the whole app going locally (as opposed to _just_ firing up R locally with googledrive and authing manually), I'm having trouble because in the container I call `shinyApp()` with `host = "0.0.0.0", port = 3838`. Locally, setting that results in:

```
Listening on http://0.0.0.0:3838
createTcpServer: permission denied
Error in .subset2(public_bind_env, "initialize")(...) : 
  Failed to create server
```

But if I turn the `host` and `port` options off, running the app locally works completely (lines I'm logging myself are marked with `*`:

```
Listening on http://127.0.0.1:7271
* Request sheet selected:
* Login button: Getting package request sheets
* Starting auth with service key @ C:/Users/rensa/Documents/mcccrh-credentials/hub-gargle-service-key.json
trying token_fetch()
trying credentials_service_account()
adding 'userinfo.email' scope
service account email: [REDACTED]
* Auth done; looking up request sheets
attempt from: googledrive
attempt from: googledrive
attempt from: googledrive
* Got the request sheets
* Login button: Updating request sheet list
attempt from: googledrive
* Login button: Updating user info
* Login button handler done
```

If I set those options when running in the container I'm able to get the Shiny image (which is based on the Rocker ones) going, but then gargle auth fails.

**Comment by rensa** [comment]
Okay, this is probably less of a googledrive issue and more of a "I've miconfigured Shiny Server" issue! I've tried ditching the `host` and `port` options in `shinyApp()` in favour of configuring the Shiny Server container properly, but I'm still ending up with the same result when I try to auth with the service account: a 400 error.

My next step might be to try and bring the MRAN date forward so I can test the CRAN release.

**Comment by jennybc** [comment]
If I do similar (but succeed), here's what I see:

```
> httr::with_verbose(drive_auth(path = rawToChar(json)))
-> POST /token HTTP/1.1
-> Host: oauth2.googleapis.com
-> User-Agent: libcurl/7.54.0 r-curl/4.0 httr/1.4.1
-> Accept-Encoding: deflate, gzip
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Type: application/x-www-form-urlencoded
-> Content-Length: 775
-> 
>> grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=[REDACTED]

<- HTTP/1.1 200 OK
<- Content-Type: application/json; charset=utf-8
<- Vary: Origin
<- Vary: X-Origin
<- Vary: Referer
<- Content-Encoding: gzip
<- Date: Wed, 02 Oct 2019 03:21:04 GMT
<- Server: scaffolding on HTTPServer2
<- Cache-Control: private
<- X-XSS-Protection: 0
<- X-Frame-Options: SAMEORIGIN
<- X-Content-Type-Options: nosniff
<- Alt-Svc: quic=":443"; ma=2592000; v="46,43",h3-Q048=":443"; ma=2592000,h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
<- Transfer-Encoding: chunked
<- 
```
 
So I see no evidence to conclude it's anything other than a problem with your token.

I note that you are behind current version on several packages. I have no specific reason to suspect that's the problem and yet, before doing further troubleshooting, updating does seem like an obvious step 1.

And then working with the same token in Docker but interactively, in Shiny but locally, and then finally in Shiny inside of Docker seems to be the next set of troubleshooting steps.

**Comment by rensa** [comment]
No, I think you're right. The only difference that stands out to me (apart from a 400 code instead of 200) is that I also have `<- content-length: 201`, although if I turn on `data_in = TRUE` in `httr::with_verbose()`, all I get printed for the return content is`<<  ▼�`.

I'll keep working on this today with the steps you suggest. If you'd like, I'm happy to close this, but I'll add a reply regardless when I figure the problem out :)

**Comment by rensa** [comment]
Reproducing this interactively in a `rocker/tidyverse:3.6.1` container (ie. no Shiny) with the same token. Here's the dockerfile:

```
FROM rocker/tidyverse:3.6.1
RUN R -e "install.packages('googledrive')"
```

Start the container as root with the service account mounted, and in R:

```r
library(tidyverse)
library(googledrive)
httr::with_verbose(drive_auth(path = 'mykey.json'), data_in = TRUE, info = TRUE)

*  Hostname oauth2.googleapis.com was found in DNS cache
*    Trying 172.217.167.74...
*  TCP_NODELAY set
*  Connected to oauth2.googleapis.com (172.217.167.74) port 443 (#4)
*  ALPN, offering h2
*  ALPN, offering http/1.1
*  Cipher selection: ALL:!EXPORT:!EXPORT40:!EXPORT56:!aNULL:!LOW:!RC4:@STRENGTH
*  successfully set certificate verify locations:
*    CAfile: /etc/ssl/certs/ca-certificates.crt
*    CApath: /etc/ssl/certs
*  SSL re-using session ID
*  TLSv1.2 (OUT), TLS handshake, Client hello (1):
*  TLSv1.2 (IN), TLS handshake, Server hello (2):
*  TLSv1.2 (IN), TLS change cipher, Client hello (1):
*  TLSv1.2 (IN), TLS handshake, Finished (20):
*  TLSv1.2 (OUT), TLS change cipher, Client hello (1):
*  TLSv1.2 (OUT), TLS handshake, Finished (20):
*  SSL connection using TLSv1.2 / ECDHE-ECDSA-AES128-GCM-SHA256
*  ALPN, server accepted to use h2
*  Server certificate:
*   subject: C=US; ST=California; L=Mountain View; O=Google LLC; CN=*.googleapis.com
*   start date: Sep  5 20:18:08 2019 GMT
*   expire date: Nov 28 20:18:08 2019 GMT
*   subjectAltName: host "oauth2.googleapis.com" matched cert's "*.googleapis.com"
*   issuer: C=US; O=Google Trust Services; CN=GTS CA 1O1
*   SSL certificate verify ok.
*  Using HTTP2, server supports multi-use
*  Connection state changed (HTTP/2 confirmed)
*  Copying HTTP/2 data in stream buffer to connection buffer after upgrade: len=0
*  Using Stream ID: 1 (easy handle 0x561aafbbe3a0)
-> POST /token HTTP/1.1
-> Host: oauth2.googleapis.com
-> User-Agent: libcurl/7.52.1 r-curl/4.2 httr/1.4.1
-> Accept-Encoding: deflate, gzip
-> Accept: application/json, text/xml, application/xml, */*
-> Content-Type: application/x-www-form-urlencoded
-> Content-Length: 795
->
>> grant_type=urn%3Aietf%3Aparams%3Aoauth%3Agrant-type%3Ajwt-bearer&assertion=[REDACTED]

*  We are completely uploaded and fine
*  Connection state changed (MAX_CONCURRENT_STREAMS updated)!
<- HTTP/2 400
<- content-type: application/json; charset=utf-8
<- vary: Origin
<- vary: X-Origin
<- vary: Referer
<- content-encoding: gzip
<- date: Wed, 02 Oct 2019 05:44:37 GMT
<- server: scaffolding on HTTPServer2
<- cache-control: private
<- content-length: 201
<- x-xss-protection: 0
<- x-frame-options: SAMEORIGIN
<- x-content-type-options: nosniff
<- alt-svc: quic=":443"; ma=2592000; v="46,43",h3-Q046=":443"; ma=2592000,h3-Q043=":443"; ma=2592000
<-
<<  ▼�

*  Curl_http_done: called premature == 0
*  Connection #4 to host oauth2.googleapis.com left intact
*  Could not resolve host: metadata.google.internal
*  Closing connection 5
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
```

**Comment by jennybc** [comment]
You've crossed into territory out of my experience. I'll continue to think about it. Personally, if I were troubleshooting, I think my next steps would be:

  * Make some non-authorized requests with googledrive, e.g. access a world-readable file, after a call to `googledrive::drive_deauth()`, to confirm the problem is specific to token flow vs a more generic problem with web traffic.
  * Use `debug()` on low-level functions in httr involved in obtaining a perishable token, based on a service account token, i.e. delve into the internals of `httr::oauth_service_token()`. It seems like that back and forth is what's failing. Compare to results from "normal", non-Docker usage.

**Comment by rensa** [comment]
Thanks a heap for the advice, @jennybc 😊 I'll have a go at some of these and conmtinue to work on it!

**Comment by rensa** [comment]
Unauthenticated results for public appear to work inside the container _provided I run `drive_deauth()` first_. If I don't, it tries to auth even for a public file, even though if I run `drive_user()` before `drive_deauth()`, I get "Not logged in as any specific Google user."

Locally, unauthenticated requests for public files work without auth even without first calling `drive_deauth()`.

But I assume that calling `drivedeauth()` is the safe assumption in most environments anyway, so this does appear to be specific to token flow.

**Comment by rensa** [comment]
Okay, I think this might be a time zone issue. Digging down into [`httr:::init_oauth_service_account()`](https://github.com/r-lib/httr/blob/af25ebd0e3b72d2dc6e1423242b94efc25bc97cc/R/oauth-server-side.R#L2) and subsequently [`httr:::jwt_signature()`](https://github.com/r-lib/httr/blob/af25ebd0e3b72d2dc6e1423242b94efc25bc97cc/R/oauth-server-side.R#L51) and printing the response, I get:

```r
content(res, "text")
# "{\n  \"error\": \"invalid_grant\",\n  \"error_description\": \"Invalid JWT: Token must be a short-lived token (60 minutes) and in a reasonable timeframe. Check your iat and exp values and use a clock with skew to account for clock differences between systems.\"\n}"
```

The Docker container is running in GMT or UTC by default, whereas my host system is running in AEST. Maybe this mismatch is stuffing things up? Will see if I can get a test container going with a local time zone to confirm.

**Comment by rensa** [comment]
```
Sys.time()
# [1] "2019-10-01 04:55:02 UTC"
```

My Docker container is running like... two days slow. 😭

**Comment by rensa** [comment]
Okay, yep—corrected the date using [the workaround](https://github.com/docker/for-win/issues/72#issuecomment-245939850) described in https://github.com/docker/for-win/issues/72, and now everything is hunky-dory authing in my containers. It looks like this problem is specific to running Docker containers in a Windows host. Unfortunately, it looks like I'll have to keep an eye on the bug until it's fixed in Docker for Windows.

I'm gonna go cry in a corner now. Thanks very much for your patience and support, @jennybc 😄

**Comment by jennybc** [comment]
Wow, what a journey!

It's really satisfying that you got to the bottom of it, though. Thanks for recording the diagnosis and solution.

**Comment by jennybc** [comment]
Also, can you provide more detail about exactly which request lead to the detailed error you included above, which lead to diagnosis? I think I know, but would prefer that you identify it.

I want to open an issue on httr re: revealing more error payload in this situation, so this sort of troubleshooting gets easier.

**Comment by craigcitro** [comment]
👍  on "what a journey" -- I've seen a lot of auth snafus in my day, and this one was still new to me.

It'd be great to get a new httr diagnostic or some other hint to save pain for the next traveler. :)

**Comment by rensa** [comment]
Ah, sorry about that! Yep, I stepped through `init_oauth_service_account()` and inspected the results of that POST call on https://github.com/r-lib/httr/blob/af25ebd0e3b72d2dc6e1423242b94efc25bc97cc/R/oauth-server-side.R#L10.

It's not super clear to me why the existing code doesn't properly print the returned error (I haven't looked through `stop_for_status()`, called on https://github.com/r-lib/httr/blob/af25ebd0e3b72d2dc6e1423242b94efc25bc97cc/R/oauth-server-side.R#L18) when you give `data_in = TRUE` to `httr::with_verbose()`. I can see that gargle must handle errors itself as part of executing different auth strategies in turn, though!

**Comment by rensa** [comment]
Just as a note to other thinking about how to handle errors from service acocunt auth in the context of a Shiny app (where you may not want it sitting on a browser prompt that a user can't act on or abandon), I'm considering wrapping `drive_auth()` in `R.utils::evalWithTimeout()` (I already use `purrr::safely()`).

Actually, I feel like `R.utils::evalWithTimeout()` would make a good purrr adverb 😄
