### ISSUE TITLE
Is the default path for application default credentials correct?

### ISSUE THREAD

**Issue by acroz** [r-lib/gargle#115]
I'm having trouble to get application default credentials to work.

When I call the application default credentials loader directly:

```r
gargle::credentials_app_default()
```

I get the following error message:

```
Error in open.connection(con, "rb") : cannot open the connection
In addition: Warning messages:
1: In file(txt) :
  'raw = FALSE' but '/home/faculty/.config/gcloud' is not a regular file
2: In open.connection(con, "rb") :
  cannot open file '/home/faculty/.config/gcloud': it is a directory
```

gargle appears to be attempting to load `~/.config/gcloud` instead of `~/.config/gcloud/application_default_credentials.json`.

Could it be that this line

https://github.com/r-lib/gargle/blob/e54eb9d68f79a905710cc8a2a5991c89a174a3a7/R/credentials_app_default.R#L96

needs to be changed to?:

```r
pth <- path_home(".config", "gcloud", pth)
```

(Prior to this line `pth` has been assigned the value `"application_default_credentials.json"`)

**Comment by jennybc** [comment]
You seem to be right. Do you want to make a PR?
