### ISSUE TITLE
Gmail API error: 408

### ISSUE THREAD

**Issue by EricGoldsmith** [r-lib/gargle#117]
Since upgrading to gargle 0.4.0 I've begun to receive timeout errors from the Gmail API when sending mail using the `gmailr`  (v1.0.0) package:

```
Gmail API error: 408
```

Reverting to gargle v0.3.1 eliminates the error. 

I'm still experimenting with things to try and narrow down the cause - but opening this issue in case:
a) others are also experiencing 
b) the developer has insights into the cause, or thoughts for further troubleshooting.

A subset of the relevant code:

```
library(dplyr)
library(lubridate)
library(gmailr)

mailResults <- function(recipients, subject, attachFilenames) {
  
  gm_auth_configure(key = getOption("ga.clientId"), secret = getOption("ga.clientSecret"))
  gm_auth(email = gargle::gargle_oauth_email())
  
  email <- gm_mime() %>%
    gm_from("no-reply@ted.com") %>%
    gm_to(recipients) %>%
    gm_subject(sprintf("%s, %s", subject, lubridate::date(now()))) %>%
    gm_html_body(subject)
  
  for (j in seq_along(attachFilenames)) {
    email <- email %>%
      gm_attach_file(attachFilenames[j], type = "image/png")
  }
  
  base::message(sprintf("Sending email to: %s", paste0(recipients, collapse = ", ")))
  gm_send_message(email)
}

options(gargle_oauth_email = TRUE)

emailRecipients <- c("user1@example.com", "user2@example.com")
chartFilenames <- c("figs/chart1.png", "figs/chart2.png")

mailResults(recipients = emailRecipients,
                subject = "Email Subject",
                attachFilename = chartFilenames)

```

**Comment by jennybc** [comment]
Can we see the full error?

It seems that, generically, 408 is a request timeout. Which could be related to the size of these attachments?

At this point, I sort of doubt the version of gargle is to blame, i.e. that may be a coincidence.

**Comment by EricGoldsmith** [comment]
>Can we see the full error?

```
Error in gmailr_POST(c("messages", "send"), user_id, class = "gmail_message",  : 
  Gmail API error: 408
  
Calls: mailResults -> gm_send_message -> gmailr_POST -> gmailr_query
Execution halted
```

The attachments are relatively small: between ~60 KB and ~950 KB. 

This code has been working for months prior to this recent timeout issue. 

I agree that the version of `gargle` seems a stretch. But, the issue was resolved by:
```
remove.packages("gargle")
devtools::install_version("gargle", version = "0.3.1", repos = "http://cran.us.r-project.org")
``` 

I'll keep digging.

**Comment by jennybc** [comment]
Maybe this should move to gmailr?

I now realize that gmailr may not be using gargle's helper for processing the response (`response_process()`), which generally makes a big step forward in revealing more info about what went wrong. I predict the API is returning a more detailed message than just the 408, so I'd focus my debugging efforts on seeing the whole payload of that response.

cc @jimhester

**Comment by EricGoldsmith** [comment]
I've now run into this Gmail API timeout issue with `gargle` v0.3.1, as well.

Apologies for the false alarm. Will continue to troubleshoot and post more details if/when they're available.

**Comment by nicocriscuolo** [comment]
Still nothing on this? Unfortunately I am encountering the same problem. Thanks!

**Comment by jhelvy** [comment]
I too have gotten inconsistent 408 errors. A week ago it worked fine for a batch of 25 emails with pdf attachments. Today got the 408. I've tried reverting to gargle v0.3.1, didn't help, same 408 error. Really puzzled with this.

**Comment by jennybc** [comment]
I don't have a sense of what gargle could do about this. I think gmailr only uses gargle for auth, not for requests and responses.
