### ISSUE TITLE
Release request

### ISSUE THREAD

**Issue by acroz** [r-lib/gargle#119]
Would it be possible to do a release? Our application depends on the fix in #116 and at present we are installing off master.

**Comment by jennybc** [comment]
OK I'll do a release in the next month:

https://github.com/r-lib/gargle/issues/120

Subscribe to that issue and/or watch this repo to see progress.

I'd like to fold a few other small fixes / features in at the same time. You can only do so many releases per period of time, so I don't want to "use" one up without putting more content in.

**Comment by acroz** [comment]
Ok, thanks for the update!
