### ISSUE TITLE
request_make() should probably default to `encode = "json"`

### ISSUE THREAD

**Issue by jennybc** [r-lib/gargle#124]
Does this work with all httr verbs?

As I work on googlesheets4 and reflecting on googledrive, I think we (almost?) always want `encode = "json"`, so that would be a much better default.

**Comment by JosiahParry** [comment]
Giving this a thumbs up. Was bamboozled by this. I was running into  `Unsupported content with type: multipart/form-data; boundary` when trying to create nested param lists. The answer was `encode = "json"`.

Reference: https://github.com/JosiahParry/gcalendr/blob/78cb7c404a84c0bd9d53c2314e8e7b51589b4ff0/R/create_event.R#L27
