### ISSUE TITLE
Lazy setting byo oauth2.0 token

### ISSUE THREAD

**Issue by vimota** [r-lib/gargle#125]
For Kaggle's BigQuery integration, we've been setting the access credentials the old way (https://github.com/Kaggle/docker-rstats/blob/master/kaggle/kaggle_bigquery.R#L46) but would like to transition to the new way of doing auth. However, since we use our own oauth token fetching mechanism we would need to use credentials_byo_oauth2 (ie. `bq_auth(scopes = NULL, token = TokenBigQueryKernel$new())`), but that forces auth to be done eagerly.

For now I think this should work:
```
auth <- getNamespace("bigrquery")$.auth
auth$set_cred(TokenBigQueryKernel$new())
auth$set_auth_active(TRUE)
```

Would this use case make sense for the library to support? Perhaps via a bq_auth_configure() using a token paremeter?

**Comment by vimota** [comment]
Ah I realized I mentioned the bigrquery method here (bq_auth_configure), but not sure if Gargle or Bigrquery is the best place to add support for this use case.

**Comment by jennybc** [comment]
What you're doing is fairly outside the scope of what I was thinking about here in gargle and with the BYO token flow. I was implicitly assuming the BYO'd token was also, originally, produced by gargle.

That said, it seems like we should be able to make this work.

What is the main goal of subclassing `Token2.0` to make `TokenBigQueryKernel`?

**Comment by vimota** [comment]
That makes sense, thanks!

The goal of TokenBigQueryKernel is to be able to auth the user of a Kaggle Notebook through our GCP integration (which uses our API instead of directly via Google). Is there a better way to do this than via a subclass of Token2.0?

**Comment by jennybc** [comment]
I haven't really thought this through but am wondering ... perhaps you should turn this inside out now and subclass `Gargle2.0`, now that it exists?

**Comment by jennybc** [comment]
But, since you presumably aren't going to, say, publish this on CRAN, I think it's possible that the sort of hack-y thing you propose in the initial comment is the way to go. Because this feels like a very special case and I'm not immediately keen on making this something officially supported in gargle.

**Comment by vimota** [comment]
That's fair, thanks for looking into it! I'll close as WAI.

**Comment by jennybc** [comment]
WAI is new to me. What does it mean? 🧐😄

**Comment by craigcitro** [comment]
WAI = Working as Intended

**Comment by jennybc** [comment]
Recording some thoughts developed in conversation with @craigcitro in another channel:

Perhaps the way to accommodate this within gargle's current design is for Kaggle to write a custom `credential_*()` function that could, conceivably, also work with a `TokenBigQueryKernel` that is a subclass of `Gargle2.0`. Then insert this new credential fetcher into gargle's registry.

This seems like it has good potential for allowing you to do what you want to do with minimal knowledge/involvement of either bigrquery or the user.

@craigcitro lets it be known that  he is happy to join me as a point of contact for thinking through this, should you wish to pursue it @vimota.

**Comment by jennybc** [comment]
That could, conceivably, even go into the released version of gargle, under the assumption that the fetcher would fail everywhere except on Kaggle and wouldn't affect the experience of anyone else. Or I suppose this could provide the impetus for gargle to provide an official method for registering *ad hoc* credential fetchers.

**Comment by vimota** [comment]
Thank you both!

Registering a custom `credential_*()` function actually sounds ideal, I'll give it a try at some point and report back!

**Comment by MarkEdmondson1234** [comment]
Custom credential functions would solve other routes such as parsing JavaScript tokens too, sounds like a nice feature


________________________________

**Comment by vimota** [comment]
Sorry to bring up this old thread, but I ended up trying your approach (to the best of my understanding).

```
library(bigrquery)
credentials_byo_kaggle <- function(scopes = NULL, token, ...) {
  cat_line("trying credentials_byo_kaggle()")
  if (inherits(token, "request")) {
    token <- token$auth_token
  }
  stopifnot(inherits(token, "TokenBigQueryKernel"))

  if (!is.null(scopes)) {
    cat_line(
      "`scopes` cannot be specified when user brings their own OAuth token; ",
      "`scopes` are already implicit in the token"
    )
  }

  token
}
options(gargle_quiet = FALSE)
gargle::cred_funs_add(credentials_byo_kaggle = credentials_byo_kaggle)
names(gargle::cred_funs_list())
bq_auth(scopes = NULL, token = TokenBigQueryKernel$new())
```

The output of `names(gargle::cred_funs_list())` looks correct: `'credentials_byo_kaggle''credentials_service_account''credentials_app_default''credentials_gce''credentials_byo_oauth2''credentials_user_oauth2'` but the rest of the output is :

```
trying token_fetch()
Error: could not find function "cat_line"
Error: could not find function "cat_line"
Error: could not find function "cat_line"
Error: could not find function "cat_line"
Error: could not find function "cat_line"
Error: could not find function "cat_line"
trying credentials_service_account()
Error: Argument 'txt' must be a JSON string, URL or file.
trying credentials_app_default()
trying credentials_gce()
trying credentials_byo_oauth()
Error: Timeout was reached: [www.kaggle.com] Resolving timed out after 10000 milliseconds
trying credentials_user_oauth2()
Gargle2.0 initialize
attempt from: bigrquery
adding 'userinfo.email' scope
loading token from the cache
no matching token in the cache
```

So it looks like the cred_funs_list I'm seeing is different from the one that's scoped to bq_auth's call to token_fetch. Is there anyway to update it from outside of the library?
