### ISSUE TITLE
Provide help when `gargle::token_fetch()` returns `NULL`?

### ISSUE THREAD

**Issue by lionel-** [r-lib/gargle#127]
gmailr was failing mysteriously, then I noticed that `gargle::token_fetch()` returned `NULL` without information.

I fixed this by removing `.R/gargle/gargle-oauth`, which was a file. Now that this is fixed, it has become a folder, perhaps this is relevant to the behaviour I was observing?

Not sure what are the appropriate actions to take here, if any. I just thought I'd post the issue I had and the steps I took to solve it.

**Comment by jennybc** [comment]
I've never heard of `.R/gargle/gargle-oauth` being a file ... so I don't have any theories about how that happened.

The general troubleshooting advice, for people who are even aware of gargle, is to make `token_fetch()` verbose, as it falls through all the credential fetching functions.

So:

``` r
options(gargle_quiet = FALSE)
```

https://gargle.r-lib.org/reference/gargle_options.html#gargle-quiet

That's mentioned in lots of vignettes, etc. But I'm not sure how we could have surfaced it to you here.
