### ISSUE TITLE
gargle fails to find credentials on Kubernetes Engine using ADC

### ISSUE THREAD

**Issue by Ozan147** [r-lib/gargle#130]
I'm trying to use `bigrquery` from within a docker container that runs on Kubernetes Engine. `credentials_app_default()` fails to authenticate and the browser option gets triggered through `credentials_user_oauth2()`. I don't experience this issue when I run the container on a GCE VM as `credentials_gce()` takes care of authentication. 

The same container runs fine on Kubernetes Engine if I replace `bigrquery` with Python's `bigquery` from `google.cloud`. As you mentioned in #78, it seems gargle's ADC strategy doesn't quite match https://cloud.google.com/docs/authentication/production:
> If the environment variable isn't set, ADC uses the default service account that Compute Engine, Kubernetes Engine, Cloud Run, App Engine, and Cloud Functions provide, for applications that run on those services.

**Comment by jennybc** [comment]
Can you set this option in an affected R session and see if we can get more info about where things are going wrong?

```
options(gargle_quiet = FALSE)

## put your bigrquery operations below here
```

**Comment by Ozan147** [comment]
Here is a minimal reproducible example:

`bigrquery` authenticates successfully through `gargle::credentials_gce()` when the following docker image runs on a GCE VM. However; authentication fails when the image runs on AI Platform Training, which uses Kubernetes Engine under the hood. Using Python's `google-cloud-bigquery` instead of `bigrquery` works fine in both cases.

Ideally, I'd expect `gargle::credentials_app_default()` to find app default credentials and handle this issue when the image runs on AI Platform Training so that I don't need to use a service account token.

Code:
```r
options(gargle_quiet = FALSE)

tb <- bigrquery::bq_project_query(
  x = "<project>", 
  query = "<sql>"
)

bigrquery::bq_table_download(x = tb)

print("DONE!")
```

Dockerfile:
```
FROM rocker/r-ver:3.6.1

RUN apt-get update && apt-get install -y --no-install-recommends \
    git-core \
    libssl-dev \
    libcurl4-gnutls-dev \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/

RUN install2.r -e \
    bigrquery
    
COPY script.R /

ENTRYPOINT ["Rscript", "script.R"]
```
Running the image on a GCE VM:
```
docker build -t test .
docker run --rm test

# trying token_fetch()
# trying credentials_service_account()
# Error: Argument 'txt' must be a JSON string, URL or file.
# trying credentials_app_default()
# trying credentials_gce()
# <resulting tibble>
# [1] "DONE!"
```
Running the image on AI Platform Training:
![logs](https://user-images.githubusercontent.com/31706804/74766234-9808ea00-524a-11ea-9bf1-7911b641e93f.png)

**Comment by jennybc** [comment]
Thanks! @craigcitro would appreciate your 👀

**Comment by jennybc** [comment]
> bigrquery authenticates successfully through gargle::credentials_gce() when the following docker image runs on a GCE VM. 

Let me also express mild, pleasant surprise about this. I don't have a good sense for how much `credentials_gce()` is getting exercised, so it's good to hear of a case where it "just works".

**Comment by MarkEdmondson1234** [comment]
I also had this experience with `credentials_gce()` this week and almost made a note, wish I did now ;)  Its working on docker containers hosted in GCP such as Cloud Run and Cloud Build, not just VMs which is super convenient (e.g. download auth files from cloud storage)   

Did also find that `credentials_app_default()` failed though, which is why I'm watching this thread

**Comment by jennybc** [comment]
Interesting!

I know through a different channel that @craigcitro suspects there may be some missing or incorrect GKE configuration that is preventing access to the GCE metadata. So having @Ozan147 and @MarkEdmondson1234 around to share details is tremendously helpful for us figuring out how to get this working.

**Comment by craigcitro** [comment]
My hunch is that we're seeing a situation where the GCE metadata service isn't visible to the job inside GKE at the usual host:port, either due to remapping or custom networking config.

I don't have cycles to send a PR right now, but I'd say we want to start by adding verbose logging at all the early exits from credentials_gce, eg:

* https://github.com/r-lib/gargle/blob/798d7d4c64421a4831ba9cf87bc1d87b11ba89ca/R/credentials_gce.R#L21
* https://github.com/r-lib/gargle/blob/798d7d4c64421a4831ba9cf87bc1d87b11ba89ca/R/credentials_gce.R#L32
* https://github.com/r-lib/gargle/blob/798d7d4c64421a4831ba9cf87bc1d87b11ba89ca/R/credentials_gce.R#L53

**Comment by Ozan147** [comment]
Thanks @jennybc, @MarkEdmondson1234 and @craigcitro for your quick replies and inputs on this. I'll be around to share additional feedback about my use case if needed. 

@MarkEdmondson1234; I'm also a frequent user and big fan of the cloudyr project. I wish `googleCloudStorageR` could also authenticate automatically from within docker containers on GCP in a similar fashion. Perhaps, cloudyr could benefit more from `gargle`.

**Comment by MarkEdmondson1234** [comment]
Here is my script I'm using to check in my tests (@Ozan147 it includes auth with GCS, and gargle is already used in all the Googley cloudyr since googleAuthR > 1.0.0)

```r
library(googleCloudStorageR)
library(gargle)

test_f <- function(token, x){
  tryCatch({
    googleAuthR::gar_auth(token = token)
    message(paste(x, " worked"))
    gcs_list_buckets("mark-edmondson-gde")
  }, error = function(ex) {
    message(paste(x, " failed"))
    message("error: ", ex)
  })
}

file.exists("~/.config/gcloud/application_default_credentials.json")

test_f(credentials_app_default(scopes = "https://www.googleapis.com/auth/cloud-platform"),
       "credentials_app_default()")

test_f(credentials_gce(scopes = "https://www.googleapis.com/auth/cloud-platform"),
       "credentials_gce()")

test_f(googleAuthR::gar_gce_auth("default", scopes = "https://www.googleapis.com/auth/cloud-platform"),
       "gar_gce_auth()")
```

If there is more debugging steps to add to it let me know, the file.exists() returns FALSE which I saw was one of the places `credentials_app_default()` is looking

I run this with a setup `googleCloudRunner` function that builds it upon a Cloud Build (which is a docker container runnning in GCP on something)

```r
cr_deploy_r("inst/schedule/test_auth.R", r_image = "gcr.io/gcer-public/googleauthr-verse")
```

The `r_image` docker image is one that includes googleCloudStorageR, gargle, googleAuthR etc.

The annotated pertinent entries from the build log are below:

```
Status: Downloaded newer image for gcr.io/gcer-public/googleauthr-verse:latest
gcr.io/gcer-public/googleauthr-verse:latest
####### the file.exisits() returns false
[1] FALSE
credentials_app_default()  failed
##### below  is error from googleCloudStorageR
error: Error: Non-interactive session and no authentication email selected. 
Setup JSON service email auth or specify email in gar_auth(email='me@preauthenticated.com')
#####
2020-02-18 21:58:30> Setting client.id from options(googleAuthR.client_id)
credentials_gce()  worked
                                           name storageClass     location
1      artifacts.mark-edmondson-gde.appspot.com     STANDARD           US
2                               bigqueryr-tests     STANDARD           US
...
gar_gce_auth()  worked
                                           name storageClass     location
1      artifacts.mark-edmondson-gde.appspot.com     STANDARD           US
...
PUSH
DONE

**Comment by Ozan147** [comment]
@jennybc & @craigcitro; I wanted to check in with you to see if this issue is on your radar. It would 
facilitate the use of R in production. Please let me know if there is anything I can help with. Stay safe!

**Comment by jennybc** [comment]
I have inserted lots of print debugging statements in `credentials_gce()`, so we should get much more information about where and why it is dying.

@Ozan147 Can you install gargle from this PR? Do it like so:

``` r
install_github("r-lib/gargle#139")
```

Then make sure to make gargle verbose by setting this option:

``` r
options(gargle_quiet = FALSE)
```

Then do anything that will cause `credentials_gce()` to get hit.

@MarkEdmondson1234 You are also warmly encouraged to also get in on this action 😁

**Comment by Ozan147** [comment]
@jennybc Thanks a lot for your time and help. Here are the GKE logs:

<img width="1320" alt="1" src="https://user-images.githubusercontent.com/31706804/80895872-49e27f00-8cae-11ea-9bd9-f2f15d30ef8a.png">
<img width="1321" alt="2" src="https://user-images.githubusercontent.com/31706804/80895879-4cdd6f80-8cae-11ea-8a71-cc8a59328357.png">

**Comment by MarkEdmondson1234** [comment]
Hmm, never seen cloud-platform.read scopes requirement before.  So does this mean

`gce_credentials(scopes = "https://www.googleapis.com/auth/cloud-platform.read-only")` works?

**Comment by Ozan147** [comment]
`garge::credentials_gce()` inherits scopes from `gargle::token_fetch()`, which is triggered by `bigrquery::bq_auth()` with the following default scopes:
```r
scopes = c(
  "https://www.googleapis.com/auth/bigquery",
  "https://www.googleapis.com/auth/cloud-platform"
)
```
These don't match the default service account scopes and auth fails.

I can successfully query BQ data from within GKE using the read-only scope:
```r
bigrquery::bq_auth(
  scopes = c(
    "https://www.googleapis.com/auth/bigquery",
    "https://www.googleapis.com/auth/cloud-platform.read-only"
  )
)
```

I also realized that [`bigrquery::bq_auth()` examples](https://github.com/r-dbi/bigrquery/blob/master/R/bq-auth.R) include a relevant case:
```r
#' ## use a 'read only' scope, so it's impossible to change data
#' bq_auth(
#'   scopes = "https://www.googleapis.com/auth/devstorage.read_only"
#' )
``` 
but GKE's read-only scope has a hyphen instead of an underscore.

I'm not sure if this read-only scope has something to do with my company's GKE settings. If not, it'd be nice to have `gargle::credentials_gce()` or `bigrquery::bq_auth()` handle this by default.

Thanks @jennybc for the PR and @MarkEdmondson1234 and @craigcitro for your insights on this!

**Comment by jennybc** [comment]
Wow, I didn't have my money on "it's a problem with `scopes`"!

I'll take a closer look this week.

But, yes, @craigcitro I think we've gotten some great data here that might make it easier for you to issue drive-by advice to me on how to improve things.

**Comment by jennybc** [comment]
Sidebar:

> but GKE's read-only scope has a hyphen instead of an underscore.

I checked and, yeah, they really are inconsistent:

https://developers.google.com/identity/protocols/oauth2/scopes

**Comment by jennybc** [comment]
@Ozan147 I think you do need to get a definitive account of the scopes associated with this service account (if it's something you / your company has set up). Or is it some automatically-generated service account? Who / what is determining the scopes?

**Comment by Ozan147** [comment]
@jennybc - Sorry that I got sidetracked and forgot about this issue. I now have better understanding of the scopes, and agree with your assessment. Thank you all for your time and effort on this!
