### ISSUE TITLE
bq_auth() relying on credentials_app_default() cannot authenticate offline with ADC 

### ISSUE THREAD

**Issue by jayBana** [r-lib/gargle#147]
`bigrquery` version 1.3.1 cannot authenticate using Application Default Credentials on Compute Engine without Internet access in GCP (instance still has access to "internal" Google Cloud Platform APIs). 

```r
bq_auth(use_oob=TRUE)

trying token_fetch()
trying credentials_service_account()
Error: Argument 'txt' must be a JSON string, URL or file.
trying credentials_app_default()
file exists at ADC path: /home/jlpuser/.config/gcloud/application_default_credentials.json
ADC cred type: authorized_user
Error: Timeout was reached: [accounts.google.com] Connection timed out after 10001 milliseconds
trying credentials_gce()
trying credentials_byo_oauth()
Error: inherits(token, "Token2.0") is not TRUE
trying credentials_user_oauth2()
Gargle2.0 initialize
attempt from: bigrquery
adding 'userinfo.email' scope
loading token from the cache
no matching token in the cache
initiating new token

Enter authorization code: 
```

The above offline ADC authentication flow works with the Python libraries on the same type of machines.

We believe that the [this line](https://github.com/r-lib/gargle/blob/master/R/credentials_app_default.R#L65) in `gargle` should look something like `endpoint <- "https://oauth2.googleapis.com/token"` as the application default credentials file includes a refresh token as per the "offline" access_type described [here](https://developers.google.com/identity/protocols/oauth2/web-server#offline). Passing the resulting token in should prevent the library from trying to acquire it's own.

I have opened an issue first in the `bigrquery` repo by mistake. [Here is the link to it](https://github.com/r-dbi/bigrquery/issues/392).

**Comment by SandorSzalma1** [comment]
I have experienced the same issue. 
Our R users cannot use AI Platform Notebook on (the company managed) GCP, they have to work with GCP from their PCs.
Hopefully this can be fixed soon!

**Comment by SandorSzalma1** [comment]
Hi Jenny,

thank you for working on this issue!

We can compare gcloud auth login (Python) with gargle (R).

gcloud auth login does not try to verify the ADC with the https:://accounts.google.com URL. It creates a link, what we pass into a new tab in the browser.

We receive a token, what we enter back to the command and it makes the verification with https://oauth2.googleapis.com

`2021-06-11 06:01:44,355 INFO     ___FILE_ONLY___ Go to the following link in your browser:
https://accounts.google.com/o/oauth2/auth?response_type=code&client_id=xxxx.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=openid+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fuserinfo.email+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcloud-platform+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fappengine.admin+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fcompute+https%3A%2F%2Fwww.googleapis.com%2Fauth%2Faccounts.reauth&state=xxx&prompt=consent&access_type=offline&code_challenge=xxx&code_challenge_method=S256
2021-06-11 06:02:12,344 DEBUG    requests_oauthlib.oauth2_session Requesting url https://oauth2.googleapis.com/token using method POST.`

I think that gargle should de the same.

**Comment by jennybc** [comment]
That sounds like getting an entirely new refresh token, using out of band auth?

This is also a scope I have never seen before and can't find any information on.

```
https://www.googleapis.com/auth/accounts.reauth
```

So this does seem to be some flow that is not on my radar.

**Comment by SandorSzalma1** [comment]
Hi Jenny,

I have reached out to Google support (as they do support R with BigQuery and it is not working in a private environment) and they gave me (us) this recommendation: 

Please take a look at the reauth code in google-auth-library-python: https://github.com/googleapis/google-auth-library-python/blob/9e1082366d113286bc063051fd76b4799791d943/google/oauth2/reauth.py

I hope it helps.

**Comment by jennybc** [comment]
Interesting! There is some stuff that, in practice, you can't implement outside of Google (i.e. you can't easily the necessary folk wisdom). @SandorSzalma1 if you have a way of finding out, is this documented anywhere besides the source of the python auth library?

**Comment by SandorSzalma1** [comment]
Hi @jennybc!

We might need with Google BigQuery something like this done for Google Sheets here: generate URL and past authorization code:
https://support.rstudio.com/hc/en-us/articles/217952868-Generating-OAuth-tokens-for-a-server-using-httr

What do you think?
