### ISSUE TITLE
Application Type Other - no longer available

### ISSUE THREAD

**Issue by muschellij2** [r-lib/gargle#149]
From https://gargle.r-lib.org/articles/get-api-credentials.html#oauth-client-id-and-secret and https://github.com/r-lib/gargle/blob/master/vignettes/get-api-credentials.Rmd#L101, I believe Application Type "Other" is outdated. I believe you have to choose Desktop Client, but I'm not 100% sure that's the type you want

**Comment by MarkEdmondson1234** [comment]
Yes it's "Desktop client" now

**Comment by jennybc** [comment]
Thanks for giving such precise info on what I needed to fix and where!
