### ISSUE TITLE
Non-interactive documentation

### ISSUE THREAD

**Issue by atreibs** [r-lib/gargle#153]
I believe that the documentation for non-interactive sessions should be updated. I spent a good amount of time trying to understand why Heroku could not authenticate my account when I realized I need to upload the .secrets file along with the other files to run properly. I don't believe that this is mentioned in the documentation and found that answer in an issue on googlesheets4.

**Comment by jennybc** [comment]
I feel like this is stated. Before we get to specific scenarios there's this about [deployment](https://gargle.r-lib.org/articles/non-interactive-auth.html#sidebar-1-deployment) (**bold** is mine):

> Let’s identify a specific type of project: it is developed in one place, with interactivity – such as your local computer – and then deployed elsewhere, where it must run without further interaction – such as on RStudio Connect or shinyapps.io. In this context, it may make sense to depart from gargle’s default behaviour, which is to store tokens outside the project, and **to embed them in the project instead**. An example at the end of this vignette demonstrates the use of a project-level OAuth cache. A service account token could also be **stored in the project**. When you **embed tokens in the project** and deploy, remember, that they are no more secure or hidden than the other source files in the project.

Then later is [Project-level OAuth cache](https://gargle.r-lib.org/articles/non-interactive-auth.html#project-level-oauth-cache):

> Obtain the token intended for non-interactive use and make sure it’s **cached in a (hidden) directory of the current project**.

**Comment by atreibs** [comment]
I suppose it wasn't clear to me that the file needed to be uploaded with the script and thought it may be helpful to include in the documentation. I do see that it is included in there to create the file and reference it in the script. 

I'm pretty new to this, as well, so this maybe user error or inexperience on my part. Someone from RStudio Community suggested I create an issue

**Comment by jennybc** [comment]
I'm just not sure more words will help? To me it feels like saying that if a script reads a specific file, say "subdir/foo.csv", that one must also make sure to upload "subdir/foo.csv" with the script. Because that is exactly what's happening. I don't see any other way one could expect things to work.
