### ISSUE TITLE
Consider analogue to secret_*() functions for non-package CI/CD workflows

### ISSUE THREAD

**Issue by petrbouchal** [r-lib/gargle#156]
First, very grateful for this package and for the many scenarios covered by the documentation.

I have been using {gargle} to auth to various Google services in a project that runs on Github Actions but is not a package. I was able to follow the workflow in https://gargle.r-lib.org/articles/get-api-credentials.html and https://gargle.r-lib.org/articles/articles/managing-tokens-securely.html but ended up using directly a lot of the code wrapped by the `gargle:::secret_*` functions, since these functions assume they are being used in the context of a package. 

Unless I am doing something wrong (which is entirely possible), would it make sense to also document the workflow for a non-package project to be deployed to Github Actions/Travic CI etc.? I suspect it might be a common enough use case. Happy to provide some wording for the vignette or even functions in a PR if you think that would be useful.

**Comment by jennybc** [comment]
I think you should look to the up-and-coming httr2 package for assistance with this:

https://httr2.r-lib.org/reference/secrets.html
