### ISSUE TITLE
Default cache folder reported on by `gargle_oauth_sitrep()`

### ISSUE THREAD

**Issue by FedericoTrifoglio** [r-lib/gargle#174]
I've just updated the package and noticed that the default cache folder has changed from `~/.R/gargle/gargle-oauth` to `~/AppData/Local/gargle/gargle/Cache`.

```
> gargle::gargle_oauth_sitrep()
[1] No gargle OAuth cache found at C:/Users/***/AppData/Local/gargle/gargle/Cache
```

I was hoping that this would change it back 

```
> options(gargle_oauth_cache = "~/.R/gargle/gargle-oauth")
```

But if I re-do,

```
> gargle::gargle_oauth_sitrep()
[1] No gargle OAuth cache found at C:/Users/***/AppData/Local/gargle/gargle/Cache
```
it still looks in `~/AppData/Local/gargle/gargle/Cache`, because the value of `rappdirs::user_cache_dir("gargle")` hasn't actually been changed by `options(gargle_oauth_cache = "~/.R/gargle/gargle-oauth")`

This of course works as Intended

```
> gargle::gargle_oauth_sitrep(cache = "~/.R/gargle/gargle-oauth")
```

But I'm not sure what `options(gargle_oauth_cache = "~/.R/gargle/gargle-oauth")` actually does then.

**Comment by jennybc** [comment]
I think you are being confused by `gargle::gargle_oauth_sitrep()`'s default behaviour. If no `cache` is specified, it defaults to the *default* cache location. Not to the current cache location. This is definitely confusing, so I need to re-think why I do this, because it sounds sub-optimal ... but I also feel like I had a reason 🤔

In my hands, setting the option **does** change the cache path.

So, if you're not using the default cache path, specify `cache` in your sitrep call, at least for now:

``` r
library(gargle)

gargle_oauth_cache()
#> [1] NA
gargle_oauth_sitrep()
#> → 11 tokens found in this gargle OAuth cache:
#>   '~/Library/Caches/gargle'
#> 
#> email                   app                scopes                      hash...   
#> _______________________ __________________ ___________________________ __________
#> jenny.f.bryan@gmail.com tidyverse-clio     ...drive                    20061ab...
#> jenny@rstudio.com       tidyverse-clio     ...drive                    20061ab...
#> jenny.f.bryan@gmail.com gargle-clio                                    6b94696...
#> jenny@rstudio.com       gargle-clio                                    6b94696...
#> jenny@rstudio.com       tidyverse-analysis ...analytics, ...webmasters 6d9268d...
#> jenny.f.bryan@gmail.com tidyverse-clio     ...spreadsheets             9566fe0...
#> jenny@rstudio.com       tidyverse-clio     ...spreadsheets             9566fe0...
#> jenny@rstudio.com       gcalendr-package   ...calendar.readonly        be9d817...
#> jenny@rstudio.com       gmailr-jenny       ...gmail.compose            d28f6f9...
#> jenny@rstudio.com       gcalendr-package   ...calendar.readonly        de4f92b...
#> jenny@rstudio.com       gmailr-jenny       ...mail.google.com          eadcb35...

(foo <- tempfile("new-gargle-cache"))
#> [1] "/tmp/RtmpKjnlUe/new-gargle-cache3b39449d86e0"

options(gargle_oauth_cache = foo)

gargle_oauth_cache()
#> [1] "/tmp/RtmpKjnlUe/new-gargle-cache3b39449d86e0"
gargle_oauth_sitrep(cache = foo)
#> → No gargle OAuth cache found at /tmp/RtmpKjnlUe/new-gargle-cache3b39449d86e0
gargle_oauth_sitrep(cache = gargle_oauth_cache())
#> → No gargle OAuth cache found at /tmp/RtmpKjnlUe/new-gargle-cache3b39449d86e0

gargle_oauth_sitrep()
#> → 11 tokens found in this gargle OAuth cache:
#>   '~/Library/Caches/gargle'
#> 
#> email                   app                scopes                      hash...   
#> _______________________ __________________ ___________________________ __________
#> jenny.f.bryan@gmail.com tidyverse-clio     ...drive                    20061ab...
#> jenny@rstudio.com       tidyverse-clio     ...drive                    20061ab...
#> jenny.f.bryan@gmail.com gargle-clio                                    6b94696...
#> jenny@rstudio.com       gargle-clio                                    6b94696...
#> jenny@rstudio.com       tidyverse-analysis ...analytics, ...webmasters 6d9268d...
#> jenny.f.bryan@gmail.com tidyverse-clio     ...spreadsheets             9566fe0...
#> jenny@rstudio.com       tidyverse-clio     ...spreadsheets             9566fe0...
#> jenny@rstudio.com       gcalendr-package   ...calendar.readonly        be9d817...
#> jenny@rstudio.com       gmailr-jenny       ...gmail.compose            d28f6f9...
#> jenny@rstudio.com       gcalendr-package   ...calendar.readonly        de4f92b...
#> jenny@rstudio.com       gmailr-jenny       ...mail.google.com          eadcb35...
```

<sup>Created on 2021-04-07 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0.9000)</sup>

Do you have a really specific reason for **not** going with the flow and accepting the new cache location?

**Comment by jennybc** [comment]
> This is definitely confusing, so I need to re-think why I do this, because it sounds sub-optimal ... but I also feel like I had a reason 🤔

I've remembered now. 

This is because I don't want mere inspection via `gargle_oauth_sitrep()` to trigger any sort of cache establishment, cleaning, or relocating. The easiest way to achieve this was to make `gargle_oauth_sitrep()` more dumb re: cache location.

I'll see if I can find a better compromise.

**Comment by FedericoTrifoglio** [comment]
I had totally missed the difference between current and default. So obvious now that you've explained it. My reason for initially being a bit reluctant to accept the new cache location is that everyone in my team has their tokens cached in `~/.R/gargle/gargle-oauth`. Thought it might happen that new tokens get stored in the new cache location, making things a bit confusing for them.

**Comment by jennybc** [comment]
My advice is to rip the bandaid off and allow gargle to move the cache. I anticipate this is a one time change, i.e. this is where the cache should have been all along.
