### ISSUE TITLE
Using an RDS exported gargle token - how to propertly import

### ISSUE THREAD

**Issue by domsle** [r-lib/gargle#175]
Hello, 

I am working with an already exported gargle token, that is exported to a RDS file. It is currently not be possible for me to retrieve another token, and for the time being it is all I have. So I cannot export it in another, more correct way. As I side note, I believe that this gargle token is very likely to have been exported from an older version of gargle library (if that matters).

The token object itself contains following structure:
```
> str(token)
Classes 'Gargle2.0', 'Token2.0', 'Token', 'R6' <Gargle2.0>
  Inherits from: <Token2.0>
  Public:
    app: oauth_app
    cache: function () 
    cache_path: [I have removed this sensitive data]
    can_refresh: function () 
    clone: function (deep = FALSE) 
    credentials: list
    email: [I have removed this sensitive data]
    endpoint: oauth_endpoint
    hash: function () 
    init_credentials: function () 
    initialize: function (email = gargle_oauth_email(), app = gargle_app(), package = "gargle", 
    load_from_cache: function () 
    package: googleAuthR
    params: list
    print: function (...) 
    private_key: NULL
    refresh: function () 
    revoke: function () 
    sign: function (method, url) 
    validate: function ()  
```
I use this token to connect to Google My Business REST API, using httr.

The example way of using the token, and accessing the data for me is:

```r
token <- readRDS("/token/location/token.rds")

try(accounts <- invisible(GET("https://mybusiness.googleapis.com/v4/accounts",
                    config(token = token)) %>%
      httr::content(as = 'parsed')))
```

That will result in an error:
```
Auto-refreshing stale OAuth token.
Error in gzfile(file, mode) : cannot open the connection
In addition: Warning message:
In gzfile(file, mode) :
  cannot open compressed file '[I have removed this sensitive data]', probable reason 'No such file or directory'

```
However in the next try the token will work, and httr::GET will return expected value. 

I assume this is caused by the token having a predefined validity period, and after is is expired it need to be updated. However, in some cases (after long calculation) I am not able predict if the token will expire. Additionally making a GET request prior to the proper request everytime is not really a good solution, as I will be making a lot of requests.

**Comment by MarkEdmondson1234** [comment]
This sounds like you saved your token before R 3.6 which changed the RDS format:
https://github.com/r-lib/gargle/pull/107 - gargle fixes it for you in that pull request. 

Perhaps if you can load it via the flag `R_DEFAULT_SERIALIZE_VERSION=2` and then rename it to a later version, via `saveRDS()` you could continue to use that token file.

**Comment by domsle** [comment]
Please forgive, but it is not clear what I should do. `readRDS` only accepts `path` and `refHook` arguments - `saveRDS` is the one that uses `version`. 
I have ran these lines, but none of the attemps to save token have solved the issue:
```
options(R_DEFAULT_SERIALIZE_VERSION=2)

token <- readRDS("old_token.RDS")
saveRDS(token, file = 'token.RDS')
token2 <- readRDS(file = 'token.RDS')
try(accounts <- invisible(GET("https://mybusiness.googleapis.com/v4/accounts",
config(token = token2)) %>%
httr::content(as = 'parsed')))

saveRDS(token, file = 'token.RDS', version = 3)
token2 <- readRDS(file = 'token.RDS')
try(accounts <- invisible(GET("https://mybusiness.googleapis.com/v4/accounts",
config(token = token2)) %>%
httr::content(as = 'parsed')))

```

By referencing the #107, do you mean to build library from this particular pull request?

**Comment by MarkEdmondson1234** [comment]
I would have tried what you did, sorry it didn't help.  The pull #107 was a bit of background to the issue.

**Comment by jennybc** [comment]
What oauth app was the token made with? We are rolling credentials in gargle, generally, right now FYI, so there's some chance I already disabled the one used to make this token. The built-in gargle app should only be used for "hello world" type experiments. And the tidyverse app can/should only be used by a very specific set of packages.

Otherwise, it's hard to say what's going on. This is not really a supported use case and I have very little visibility into what this token is, etc. 

> It is currently not be possible for me to retrieve another token

I realize that you probably realize this, but OAuth tokens are basically meant to be fairly perishable and easily replaceable, so it's a tough position to be in.

If you absolutely must make this work, you probably need to use `debug()` on some of the internal httr functions involved in token refresh and get a better look at exactly where that's failing.

**Comment by jennybc** [comment]
Is this issue still "live"? Otherwise, I'll close it soon.
