### ISSUE TITLE
How to automate refresh access token using gargle inside own client package

### ISSUE THREAD

**Issue by selesnow** [r-lib/gargle#182]
Hello Jenny, thank for gargle. 

i using gargle package for auth inside my own package.

I am create all auth function from vignnet https://cran.r-project.org/web/packages/gargle/vignettes/gargle-auth-in-client-package.html

I get access_token, and it expire after 3600 second, next i can refresh it using .auth$cred$refresh(), but i dont`t know how do it automaticly.

Could you help me?

**Comment by jennybc** [comment]
It should happen automatically, i.e. this is a property of the token object (at least for refreshable token types).

Are you actually experiencing a problem or are you just anticipating a problem?

If you're experiencing problem, please provide more details and maybe I can help spot the reason why you aren't enjoying automatic refresh.

**Comment by selesnow** [comment]
Thanks, now i writing package for work with Google Ads API, and use gargle for auth.

When i use `load_all()` i must manualy run `.auth$cred$refresh()`, maybe i need builded package, and then this works automaticly?

**Comment by jennybc** [comment]
> When i use load_all() i must manually run .auth$cred$refresh(), maybe i need builded package, and then this works automatically?

A manual `$refresh()` makes it sounds like something is wired up wrong. If the code is somewhere public, I could take a quick look and see I can spot a problem.

**Comment by selesnow** [comment]
Yes, i push all to [gads_auth.R](https://github.com/selesnow/rgoogleads/blob/master/R/gads_auth.R).

**Comment by selesnow** [comment]
And, i get the string of access_token, for my api request [like this](https://github.com/selesnow/rgoogleads/blob/master/R/gads_get_report_helper.R#L81).

**Comment by jennybc** [comment]
Yes, I think your diagnosis is correct. The automatic self-refreshing property comes from a full `Token2.0` object, which is an instance of an R6 class that has a `$refresh()` method. If you surgically pull out just the access token (literally that string), it won't have the ability to refresh itself gracefully in an http request.

**Comment by jennybc** [comment]
For your development, if you can, I suggest that you use a service account token. That's what I do in googledrive and googlesheets4. The token is loaded in `tests/testthat/helper.R`, which also means it's loaded by `devtools::load_all()`.

https://github.com/tidyverse/googlesheets4/blob/a291cf33bd4ba5fbd6f9272034a18fb714a9385a/tests/testthat/helper.R#L1-L8

https://github.com/tidyverse/googlesheets4/blob/d3df9b452b6020ab073614efb6845174c6c520e7/R/gs4_auth.R#L263-L301

**Comment by selesnow** [comment]
Thanks Jenny, i added

```
  # check token
  gargle::token_tokeninfo(gads_token())
```

 in all my package function and now it seems the token is automatically refreshed

**Comment by jennybc** [comment]
I don't advocate the inclusion of `gargle::token_tokeninfo(gads_token())` in all package functions. I stick by my claim that this should not be necessary and indicates something else is wired up wrong.

But it's also not going to hurt anything, I suppose.

**Comment by selesnow** [comment]
Hello,

My mistake was that I used a `httr::GET()`, `httr::POST()`, `httr::content()` instead of a `gargle::request_build()`, `gargle::request_retry()` and `gargle::response_process`.

As soon as I fixed this, the authorization began to work and automatically update the credentials correctly.

**Comment by jennybc** [comment]
Glad to hear it!

You don't _need_ to use the gargle functions to form and make a request. After all, we just use `httr::GET()`, `httr::POST()`, etc. also.

But I think this shows that the previous way you were incorporating the token was the problem. And, by using the gargle functions, the token is getting adding to the request in the intended way, which allows tokens to refresh themselves.
