### ISSUE TITLE
Error: Could not authenticate via any gargle cred function

### ISSUE THREAD

**Issue by arthurlin-kmd** [r-lib/gargle#188]
Hi there,

I want to use googleanalyticsR and have set up client.json on the google cloud platform. I am unable to authenticate through ga_auth() and have been getting the error message "Error: Could not authenticate via any gargle cred function". Below are the code to reproduce the error, and output I am seeing.

```r
# Code to reproduce
library(googleAnalyticsR)
library(googleAuthR)

googleAuthR::gar_set_client("~/Documents/Rstudio/client.json")
googleAnalyticsR::ga_auth()

```

```r
# Output
> googleAuthR::gar_set_client("~/Documents/RStudio/client.json")
√ Setting client.id from ~/Documents/RStudio/client.json
[1] "client.id"
> googleAnalyticsR::ga_auth()
i 2021-08-27 22:06:23 > Using email from GARGLE_EMAIL env var: XXXX@gmail.com
Error: Could not authenticate via any gargle cred function
```

**Comment by arthurlin-kmd** [comment]
Hi @MarkEdmondson1234  thanks for your prompt reply.

I have removed GARGLE_EMAIL from R_environ file, but I still cannot auth. The issue now is that Rstudio hangs when I execute ga_auth(), whereas I was expecting to see a prompt on the web browser to authenticate API access. Below are the codes to reproduce and the output.

Thank you for your help and gift of time!

````r
# Code to reproduce
library(googleAnalyticsR)
library(googleAuthR)

googleAuthR::gar_set_client("~/Documents/Rstudio/client.json")
googleAnalyticsR::ga_auth(email = "XXXX@gmail.com")
````

````r
# Output
> googleAuthR::gar_set_client("~/Documents/RStudio/client.json")
√ Setting client.id from ~/Documents/RStudio/client.json
[1] "client.id"
> googleAnalyticsR::ga_auth(email = "XXXX@gmail.com")


<Rstudio hangs from this point onwards>


````

**Comment by MarkEdmondson1234** [comment]
Is the browser not opening? Try without the email argument. Also please put on options(googleAuthR.verbose = 2) to get more logging information

**Comment by arthurlin-kmd** [comment]
hi @MarkEdmondson1234 

I attempted to include `options(googleAuthR.verbose = 2)` alongside what I had before, and below is what I have in the output. I noticed both `googleAuthR.webapp.client_id='  '` and `googleAuthR.webapp.client_secret='  '`, does this mean I have missed out a step in Google Cloud Project and the authentication process was not set up correctly? 

```r
# Code to reproduce
library(googleAnalyticsR)
library(googleAuthR)

options(googleAuthR.verbose=2) 
googleAuthR::gar_set_client("~/Documents/Rstudio/client.json")
googleAnalyticsR::ga_auth(email = "XXXX@gmail.com")
```

```r
# Output
> # This is a test script for extracting data from GA----
> library(googleAnalyticsR)
√ Setting client.id from ~/Documents/RStudio/client.json
i 2021-08-29 13:04:18 > No consent file found
You can opt in to tracking of your use of googleAnalyticsR - see ?measurementProtocol::mp_trackme for details.
Warning message:
package ‘googleAnalyticsR’ was built under R version 4.0.5 
> library(googleAuthR)
Warning message:
package ‘googleAuthR’ was built under R version 4.0.5 
> options(googleAuthR.verbose=2) 
> googleAuthR::gar_set_client("~/Documents/RStudio/client.json")
√ Setting client.id from "~/Documents/RStudio/client.json"
i 2021-08-29 13:04:23 > 
options(googleAuthR.scopes.selected=c(' https://www.googleapis.com/auth/analytics','https://www.googleapis.com/auth/analytics.readonly','https://www.googleapis.com/auth/analytics.edit','https://www.googleapis.com/auth/analytics.manage.users','https://www.googleapis.com/auth/analytics.user.deletion ')) 
options(googleAuthR.client_id=' client_id.apps.googleusercontent.com ') 
options(googleAuthR.client_secret=' client_secret') 
options(googleAuthR.webapp.client_id='  ') 
options(googleAuthR.webapp.client_secret='  ')
[1] "ga-kmdr-api-access"
> ga_auth()
Error: Could not authenticate via any gargle cred function
> 
```

**Comment by arthurlin-kmd** [comment]
Hi @MarkEdmondson1234,

I was wondering if you had a chance to review my previous comment? Thanks!

**Comment by MarkEdmondson1234** [comment]
Would you mind moving this to googleAnalyticsR issues? Just so as not to bother gargle maintainers. 

I can't see anything why it is not working, try a fresh R restart and don't set any options() yourself (Save the debug) Also use the `ga_auth_setup()` function to set client etc. as that will do checks to ensure things are as they should be.  See https://code.markedmondson.me/googleAnalyticsR/articles/setup.html

**Comment by arthurlin-kmd** [comment]
@MarkEdmondson1234 thanks I will close this one with gargle.
