### ISSUE TITLE
Generated token gets associated with different project number

### ISSUE THREAD

**Issue by domsle** [r-lib/gargle#192]
Hello,

I am trying to access Google My Business using the API. To do so, I am create a token:

```r
token <- gargle::credentials_user_oauth2(
  scopes = c('https://www.googleapis.com/auth/business.manage'),
  key = '5662xxxxxxx.apps.googleusercontent.com',
  secret = 'xxxxx', 
  email = 'xxxxx',
  use_oob = TRUE)
```

Once successfully authenticated, I am presented with a different project number in token_tokeninfo():

```r
> gargle::token_tokeninfo(token)
$azp
[1] "60336xxxxxx.apps.googleusercontent.com"

$aud
[1] "60336xxxxxx.apps.googleusercontent.com"

$sub
[1] "xxxx"

$scope
[1] "openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/business.manage"

$exp
[1] "1633016056"

$expires_in
[1] "3599"

$email
[1] "xxxx"

$email_verified
[1] "true"

$access_type
[1] "offline"

```
Can this behavior be caused by an error in gargle? 

This might be the reason of the problem I encounter later in a request:

```r
> (accounts <- GET("https://mybusiness.googleapis.com/v4/accounts",
+                 config(token = token)) %>%
+   httr::content(as = 'parsed'))
$error
$error$code
[1] 403

$error$message
[1] "Google My Business API has not been used in project 60336xxxx before or it is disabled. Enable it by visiting https://console.developers.google.com/apis/api/mybusiness.googleapis.com/overview?project=60336xxxx then retry. If you enabled this API recently, wait a few minutes for the action to propagate to our systems and retry."

$error$status
[1] "PERMISSION_DENIED"

[some more details of the error removed]
```

According to Google Support my account should be able to access this API - I have completed a necessary form.

**Comment by jennybc** [comment]
``` r
token <- gargle::credentials_user_oauth2(
  scopes = c('https://www.googleapis.com/auth/business.manage'),
  key = '5662xxxxxxx.apps.googleusercontent.com',
  secret = 'xxxxx', 
  email = 'xxxxx',
  use_oob = TRUE)
```

I assume this is sort of impressionistic, as `gargle::credentials_user_oauth2()` does not process arguments `key` and `secret`.

But since this question is *about* "project number", this could indeed be part of the problem, if you are literally passing `key` and `secret` as above. Because they will not be used. Perhaps you want to use the `app` argument?

What aspect of what you see from `token_tokeninfo()` do you perceive to be wrong? Literally, which of those fields? And can you describe it as "I expected XYZ but the value is ABC".

> According to Google Support my account should be able to access this API - I have completed a necessary form.

When you say form, do you mean you have enabled this specific API, for the project whose OAuth app you are using, in the developer console?

**Comment by domsle** [comment]
I am sorry, I got confused somehow.

Of coarse, adding an app argument, with mine key and secret solved this issue.

Thanks for the help :)

**Comment by domsle** [comment]
I have a follow-up question to this kind of setup. I have managed to auth successfully by using your suggestions, so by running this code:
``` r
token <- gargle::credentials_user_oauth2(
  scopes = c('https://www.googleapis.com/auth/business.manage'),
  app = httr::oauth_app(
    appname = '[xx]',
    key = '[xxxxxx].apps.googleusercontent.com',
    secret = '[xxxx]'
  ),
  email = '[xxxx]@gmail.com',
  use_oob = TRUE)
```

Further in my workflow I save the token to a RDS file, and in case of using this token again (every day) I use it by importing this file, and later passing it to httr's POST or GET, in config argument, like this:
``` r
downloaded <- GET(
        url = paste0(
          "https://mybusiness.googleapis.com/v4/accounts/",
          account,
          '/locations/',
          location,
          '/reviews'
        ),
        config(token = token)
      )
```

The problem I am encoutering now, it that the refresh token located in my `/home/user/.R/gargle/gargle-oauth/tokenfile_with_long_name` is removed after I week.

My workflow works, because everytime I try to access a resource with expired token (which was read from RDS), it is refreshed using file in the path above. But after a week (right now it was exactly a week, for the previous one I would need to dig into logs), it just seem to get deleted. The error I get when accessing a resource:

```
Error : [ENOENT] Failed to remove '/home/dominik/.R/gargle/gargle-oauth/[some-censored-data]@gmail.com': no such file or directory
In addition: Warning message:
Unable to refresh token: invalid_grant
``` 
 I am 100% sure that there is no what that there is an accidental removal of this token from this location.


Shall I open a new issue with this, or proceed here?

**Comment by jennybc** [comment]
First, yeah, always better to open a new issue.

At first blush, I'm not sure what gargle's role in this might be. I've never encountered this specific problem before, which makes me wonder if maybe ... your Google Workspace admin has set some sort of policy re: how long refresh tokens are valid? Or is it something specific to that API?

When / if you open a new issue, please state your OS, gargle version, maybe some info from `gargle::gargle_oauth_sitrep()`, etc.
