### ISSUE TITLE
Suggested function renaming

### ISSUE THREAD

**Issue by hadley** [r-lib/gargle#2]
```
get_application_default_credentials -> credentials_app_default
get_gce_credentials ->                 credentials_gce
get_service_account_credentials ->     credentials_service_account
get_travis_credentials ->              credentials_travis
get_user_oauth2_credentials ->         credentials_user_oauth2
```

A common prefix is better for autocomplete, IMO.

**Comment by jennybc** [comment]
I can do this while I figure out how to use this package.

The 5 credential-getters above are a logical group to rename *en masse*.

Is the idea to end the renaming there?

Or to generally do `object_otherstuff`? If the latter, are these workable ideas for the remaining exported functions?

  * tokens:
    - `fetch_token() -> token_fetch()`
    - *you can imagine there might be more `token_*()` functions ...*
  * credential functions:

    ```
    add_credential_function ->          credfuns_add()
    all_credential_functions ->         credfuns_list()
    set_credential_functions ->         credfuns_set()
    set_default_credential_functions -> credfuns_set_defaults()
    ```

**Comment by craigcitro** [comment]
I'm indifferent on names -- happy to go with whatever folks find the most useful.

(I'll also point out that the `get_*_credentials` functions already *do* have a common prefix. 😛 )

In general, I suspect that 90+% of users won't need anything but `fetch_token`.

**Comment by hadley** [comment]
@jennybc yes, in general, I think that's a better naming scheme because it works better with autocomplete. But as @craigcitro it's not hugely important as most users won't see. But still worth doing IMO.
