### ISSUE TITLE
Custom error types for http responses

### ISSUE THREAD

**Issue by MarkEdmondson1234** [r-lib/gargle#201]
During a r-lib/targets pull request review I had feedback to make the error conditions specific to the HTTP response type, and now its done I find it very helpful when building the Google API responses since you can do logic based on specific status code.

For example, creating a BigQuery table gives a 409 status error code if it already exists.  This can be parsed via tryCatch similar to:

```r
tryCatch(
    bqr_create_table(
      tableId = tableId,
      timePartitioning = TRUE
    ),
 error_409 = function(err){
    message("Table already exists")
  },
 error = function(err){
    stop(err$message)
})
```

This is nicer than before checking for the status code in the response myself etc.

I put this in `googleAuthR` using `rlang` via:

```r
abort_http <- function(status_code, msg = NULL){
  rlang::abort(paste0("http_",status_code), 
               message = paste0("http_", status_code, " ", msg)
  )
}
```

https://github.com/MarkEdmondson1234/googleAuthR/commit/e1df597a60efc443de8297439322a85247a19581

...and thought it may be a nice addition to `gargle` - what do you think?

**Comment by jennybc** [comment]
gargle already does throw classed errors, in general.

In terms of processing a response, that includes `"gargle_error_request_failed"` and also `glue("http_error_{httr::status_code(resp)}")`.

Are you already aware of this?

https://github.com/r-lib/gargle/blob/1e67aa0c18c4714b0056396029bd3c0a34a98af5/R/response_process.R#L128-L138

**Comment by MarkEdmondson1234** [comment]
I was not - what a good idea ;). Ok all good then.
