### ISSUE TITLE
object 'type' not found in request_retry()

### ISSUE THREAD

**Issue by selesnow** [r-lib/gargle#205]
Hello, i has next error when using in `request_retry()`, 

```
Error in eval(parse(text = text, keep.source = FALSE), envir) :
object 'type' not found
```

but if i use `request_make()` + `response_process()` i has message `429 Resource Exhausted`.

**Comment by jennybc** [comment]
I'm afraid I'll need more information to dig into this.

Such as a full backtrace and, ideally, some code I can run to experience the error myself. I'm closing this for now, but if you can provide the above, feel free to open a new issue.
