### ISSUE TITLE
Gargle not receiving or saving the refresh token

### ISSUE THREAD

**Issue by StatisMike** [r-lib/gargle#215]
I am currently in process of wrapping up `gargle` as a way of handling google RAPI for my package. I've created an app that will be associated with the package in *Google Cloud Console* and API key, incuding them also in the package.

As far as getting the new token - everything works as intended. That's the output that i get with gargle debug verbosity:
```r
> deepgsheets4::deepgs_auth()
trying `token_fetch()`
trying `credentials_service_account()`
Error caught by `token_fetch()`:
Argument 'txt' must be a JSON string, URL or file.
trying `credentials_external_account()`
aws.ec2metadata not installed; can't detect whether running on EC2 instance
trying `credentials_app_default()`
trying `credentials_gce()`
trying `credentials_byo_oauth()`
Error caught by `token_fetch()`:
inherits(token, "Token2.0") is not TRUE
trying `credentials_user_oauth2()`
Gargle2.0 initialize
adding "userinfo.email" scope
loading token from the cache
The deepgsheets4 package is requesting access to your Google account.
Select a pre-authorised account or enter '0' to obtain a new token.
Press Esc/Ctrl + C to cancel.

1: statismike@gmail.com

Selection: 0
no matching token in the cache
initiating new token
Waiting for authentication in browser...
Press Esc/Ctrl + C to abort
Authentication complete.
putting token into the cache:
~/.cache/gargle
```
Problem is apparent when trying to refresh the access token. After checking inside the `.auth` of both `googledrive` and package I'm authoring, it looks that the refresh token is not saved.
```r
> googledrive:::.auth$cred$credentials |> str()
List of 6
 $ access_token : chr  __truncated__
 $ expires_in   : int 3599
 $ refresh_token: chr  __truncated__
 $ scope        : chr "openid https://www.googleapis.com/auth/userinfo.email https://www.googleapis.com/auth/drive"
 $ token_type   : chr "Bearer"
 $ id_token     : chr  __truncated__
> deepgsheets4:::.auth$cred$credentials |> str()
List of 5
 $ access_token: chr  __truncated__
 $ expires_in  : int 3599
 $ scope       : chr "https://www.googleapis.com/auth/spreadsheets https://www.googleapis.com/auth/userinfo.email openid"
 $ token_type  : chr "Bearer"
 $ id_token    : chr  __truncated__
```
Could this be connected with my oauth app on google console being available currently only in developer mode with only my gmail address allowed?

All gargle auth functions are gathered here: https://github.com/StatisMike/deepgsheets4/blob/main/R/auth.R

UPDATE: Also, I think I should give the output of `sitrep()`:
```r
> gargle:::gargle_oauth_sitrep()
2 tokens found in this gargle OAuth cache:
~/.cache/gargle

email                app            scopes          hash...   
____________________ ______________ _______________ __________
statismike@gmail.com tidyverse-clio ...drive        20061ab...
statismike@gmail.com deepgs4_dev    ...spreadsheets f443df1...
```

**Comment by StatisMike** [comment]
@jennybc Thanks for quick reply and correct recognition of the problem!

I've defined my Oauth app as *web app*. After creating app as a *desktop app* the refresh token is generated and stored. 

I think this was a sole source of this problem, so I guess the only added benefit for future users would be to add this information about how Oauth app should be defined in vignette *How to use gargle for auth in a client package* (unless this information is already available somewhere else in the documentation, and I just didn't saw it).

**Comment by jennybc** [comment]
Indeed we do state that you should get an oauth client of type "desktop application":

https://gargle.r-lib.org/articles/get-api-credentials.html#oauth-client-id-and-secret

In a future version, gargle will have some limited support for oauth clients of type "web app", so this article will get an update.

But for you, for now, you are probably suffering from this:

https://stackoverflow.com/questions/10827920/not-receiving-google-oauth-refresh-token/10857806#10857806

And *also* not requesting "offline" access.
