### ISSUE TITLE
Oauth scopes are being ignored during credentials_gce() auth flow

### ISSUE THREAD

**Issue by Tilenk** [r-lib/gargle#216]
Hi,
we're having problems setting scopes in credentials_gce() because the scopes are being ignored at [credentials_gce.R](https://github.com/r-lib/gargle/blame/8749ceaba896253ac21648f05f6798285205b2a3/R/credentials_gce.R#L146).

Our RStudio connect pod runs with a different GKE service account that's binded to a separate IAM service account. This service account is different from the one that's attached to our node pool. We tried adding default oauth scopes to the node pool, but that didn't have any effect.

We would like to have the ability to set the scopes with gargle, because other solutions include downloading the service account and attaching it to the pod which are not secure.

My proposed solution is to add the scopes in fetch_gce_access_token function:
```r
fetch_gce_access_token <- function(scopes, service_account) {
  path <- glue("instance/service-accounts/{service_account}/token")
  if(!is.null(scopes)) {
    scopes <- paste(scopes, collapse = ",")
    path <- glue("{path}?scopes={scopes}")
  }
  response <- gce_metadata_request(path)
  httr::content(response, as = "parsed", type = "application/json")
}
```

**Comment by jennybc** [comment]
Just checking in to confirm that yes I agree this is a problem. I have gotten myself into a position (with a VM on GCE) to work on it.

**Comment by jennybc** [comment]
I actually think `scopes` should not even be an argument in the GCE functions. We are giving a false impression that you can specify `scopes` when in fact you cannot.

With `credentials_gce(service_account = "default")`, we auth as the specified `service_account`. And *that* is where the scopes can / must be configured.

https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances#applications

> Note: You can use the access token only for scopes that you specified when you created the instance. For example, if the instance has been granted only the `https://www.googleapis.com/auth/storage-full` scope for Cloud Storage, then it can't use the access token to make a request to BigQuery.

https://cloud.google.com/compute/docs/metadata/default-metadata-values

> service-accounts/
> A directory of service accounts associated with the VM. For each service account, the following information is available: ...
> scopes: The access scopes assigned to the service account.

So I think you need to create a service account with the scopes you need, enable it for your instance, then specify that service account.

https://cloud.google.com/compute/docs/access/create-enable-service-accounts-for-instances

**Comment by jennybc** [comment]
I have used the googleComputeEngineR package to launch a VM on GCE and experience the `credentials_gce()` flow myself. So I see the failure you're talking about, but was able to fix it by adding the necessary scopes at instance creation time. I'm not sure how you are creating your VMs, but hopefully this demo helps regardless.

Prereq: I did the [necessary setup for googleComputeEngineR](https://cloudyr.github.io/googleComputeEngineR/index.html).

Then I created an instance:
 
``` r
library(googleComputeEngineR)

vm <- gce_vm(
  template = "rstudio",
  name = "gargle-gce-rstudio-server",
  username = "jenny",
  password = "jenny1234",
  serviceAccounts = list(
    list(
      scopes = c(
        "https://www.googleapis.com/auth/cloud-platform",
        "https://www.googleapis.com/auth/drive"
      )
    )
  ),
  predefined_type = "e2-standard-4"
)
```

Then I log in at the IP address revealed for the VM.

And over in an R session there I can do (NOTE: this is just using the default GCE service account, without doing anything special):

``` r
library(googledrive)

# workaround for https://github.com/r-lib/gargle/issues/221
options(httr_oauth_cache = FALSE)

chicken_csv <- drive_example_local("chicken.csv") %>%
  drive_upload("chicken-upload.csv")
#> Local file:
#> • '/usr/local/lib/R/site-library/googledrive/extdata/example_files/chicken.csv'
#> Uploaded into Drive file:
#> • 'chicken-upload.csv' <id: 1Ej3U3HzCbDnEV63MoHcY6g5D-J03hPIE>
#> With MIME type:
#> • 'text/csv'

drive_find()
#> # A dribble: 1 × 3
#>   name               id                                drive_resource   
#>   <chr>              <drv_id>                          <list>           
#> 1 chicken-upload.csv 1Ej3U3HzCbDnEV63MoHcY6g5D-J03hPIE <named list [41]>

drive_rm(chicken_csv)
#> File deleted:
#> • 'chicken-upload.csv' <id: 1Ej3U3HzCbDnEV63MoHcY6g5D-J03hPIE>
```

<sup>Created on 2022-10-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jennybc** [comment]
In case it's helpful, you can use some unexported gargle functions to see which service accounts are available and what scopes are enabled:

``` r
x <- gargle:::gce_metadata_request("instance/service-accounts/default/scopes")
x |> 
  httr::content(as = "text", encoding = "UTF-8") |> 
  strsplit(split = "\n", fixed = TRUE)
#> [[1]]
#> [1] "https://www.googleapis.com/auth/cloud-platform"
#> [2] "https://www.googleapis.com/auth/drive"
```

<sup>Created on 2022-10-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by jennybc** [comment]
I see that you say:

> We tried adding default oauth scopes to the node pool, but that didn't have any effect.

Are you 100% sure you are successfully enabling those scopes?

Possibly relevant:

https://stackoverflow.com/questions/39855989/cant-access-metadata-token-for-service-account-from-google-container-vm-image

**Comment by jennybc** [comment]
More notes to self: It's all coming back now. These previous discussions are helping me remember the relevant back story:

#161
#185

**Comment by Tilenk** [comment]
Hey @jennybc, thank you for looking into this issue. There where several developments during between Oct and now (Jan). We have been running GKE with worker identity that get its tokens from GKE (not GCE) metadata server. GKE metadata server has a bug that doesn't attach the scopes that we defined while creating the node pool. We switch from GKE to GCE metadata server which solved our issue with the scopes.

Although access scopes are still used in GCP they are [out of fashion](https://cloud.google.com/iam/docs/best-practices-service-accounts#access-scopes). Google recommends adding _https://www.googleapis.com/auth/cloud-platform_ to all [newly created VM ](https://cloud.google.com/compute/docs/access/service-accounts?&_ga=2.227776861.-1935163540.1660311854#scopes_best_practice)
But the problem here is that sometimes we need to add a scope to access non gcp apis, like google sheets. If you are running GCE it's easy to stop the VM add the scopes and start it again. But on other google compute services this is complicated (like GKE) or simple not possible (cloud run).
Looking at the official [google auth lib](https://github.com/googleapis/google-auth-library-python/blob/a83af399fe98764ee851997bf3078ec45a9b51c9/google/auth/compute_engine/_metadata.py#L237) adding scopes via code is support for GCE. We are used to adding scopes via code and we got confused why adding scopes in gargle doesn't work.

**Comment by jennybc** [comment]
Thanks for the link to the relevant bit of the Python library. I'll pursue that.

**Comment by jennybc** [comment]
Once I merge #247, gargle will pass scopes along when getting the access token on GCE.

In my hands, these scopes have no effect on the scopes associated with the resulting token, which I have documented for myself in an internal article, also in #247. I always get a token with the scopes determined when the instance was created/started.

However, I note that it doesn't seem to hurt anything if I ask for scopes I don't have. And perhaps in your, more complicated setting, this actually has the desired effect? I have to assume that the Python auth library does this for a reason, so I'm willing to try doing the same.
