### ISSUE TITLE
Gargle renew token fails if Google password changes

### ISSUE THREAD

**Issue by saudiwin** [r-lib/gargle#228]
Hard to reproduce this, but it seems that the re-auth fails if a Google password changes. I was caching credentials with the following code in `googlesheets4`:

```
gs4_auth(
  cache = ".secrets",
  email = "xxx@xxx.edu"
)
```

Which worked fine until I changed my password. Then I got this error:

```
Error in `gargle_abort_request_failed()`:
! Client error: (401) UNAUTHENTICATED
• Request not authenticated due to missing, invalid, or expired OAuth token.
• Request had invalid authentication credentials. Expected OAuth 2 access token, login cookie or
  other valid authentication credential. See
  https://developers.google.com/identity/sign-in/web/devconsole-project.
Run `rlang::last_error()` to see where the error occurred.
Warning message:
Unable to refresh token: invalid_grant
• Bad Request 
```

This was easy to fix, I simply did `gs4_deauth()` to remove the token and then re-authenticated without a problem. Seems like something though that could be tried if `gargle` gets this error by default in the function.

**Comment by jennybc** [comment]
I don't think gargle can really do anything about this. It's going to happen whenever the semi-persistent refresh token becomes invalid, which can happen for many reasons. And we've just learned that changing your password seems to be one of them.

Once a token fails to refresh, it _should_ automatically be removed from the cache and your next attempt to auth should trigger a fresh oauth dance.

BTW `gs4_deauth()` doesn't remove a cached token. It just puts googlesheets4 into "deauth'ed" mode.

**Comment by jennybc** [comment]
My impression is there's no action item here.
