### ISSUE TITLE
Create skip_if_no_token()

### ISSUE THREAD

**Issue by jennybc** [r-lib/gargle#29]
Create `skip_if_no_token()` based on the version in googledrive. But hopefully simpler.

**Comment by hadley** [comment]
I'd structure it more like this:

```R
has_token <- function() {
  env_var <- as.logical(Sys.getenv("GOOGLEDRIVE_LOAD_TOKEN", NA_character_))
  if (isFALSE(env_var)) {
    message("Not attempting to load token")
    return(FALSE)
  } 
  
  token <- tryCatch(
    {
      drive_auth(rprojroot::find_testthat_root_file("testing-token.rds"))  
      TRUE
    }
    ,
    warning = function(x) FALSE,
    error = function(e) FALSE
  )
  if (!token) {
    message("Unable to load token")
  }
  
  token
}

skip_if_no_token <- (function() {
  has_token <- NULL
  function() {
    has_token <<- has_token %||% has_token()
    testthat::skip_if_not(has_token, "No Drive token")
  }
})()
```

**Comment by jennybc** [comment]
👆 is present and working in googledrive (https://github.com/tidyverse/googledrive/commit/baf495ac8d1174b8fc28299f1af7af0a8b9bb605)

**Comment by jennybc** [comment]
We've got `skip_if_no_auth()` here in gargle and client packages should do something like this, from googledrive:

https://github.com/tidyverse/googledrive/blob/52d9082ff314a701b4162c35cbd7da540207f4c9/tests/testthat/helper.R#L6-L8

I don't see any pressing issue here.
