### ISSUE TITLE
Provide tools and instructions for embedding an encrypted token

### ISSUE THREAD

**Issue by hadley** [r-lib/gargle#3]
And include some docs about how to create, encrypt, and decrypt.

**Comment by hadley** [comment]
In the same way the json service tokens have a standard location on GCE, we should adopt a standard location on travis.

**Comment by hadley** [comment]
Plus advice to package authors about how to run API tests on travis

**Comment by jennybc** [comment]
I'm adapting @hadley's approach from bigrquery and porting it over here. Will provide functions and instructions for how to embed an encrypted service account token that can be activated locally, on travis (or anywhere private env vars are allowed), on r-hub.
