### ISSUE TITLE
Get rid of the magrittr dependency

### ISSUE THREAD

**Issue by jennybc** [r-lib/gargle#33]
Thoughts @hadley? Currently `%>%` is used 5x in `gce-token.R` and that's it. It wouldn't be hard to remove. So far gargle's dependencies are quite minimal and I've gone to some trouble to not use purrr. If it's likely to get pulled in eventually, it would be nice to predict that and save myself some grief. But I think it can be avoided.

**Comment by hadley** [comment]
Yeah, get rid of it. I tend to avoid magrittr dependency in pacakges too (especially since it makes debugging slightly worse)
