### ISSUE TITLE
Response processing + error message helper

### ISSUE THREAD

**Issue by hadley** [r-lib/gargle#36]
Seems like we should encode all our knowledge about error messages in one place. bigquery currently has this:

```R
signal_reason <- function(reason, message) {
  if (is.null(reason)) {
    stop(message, call. = FALSE)
  } else {
    cl <- c(paste0("bigrquery_", reason), "error", "condition")
    message <- paste0(message, " [", reason, "]")

    cond <- structure(list(message = message), class = cl)
    stop(cond)
  }
}
```

**Comment by craigcitro** [comment]
One more relevant link from the sidelines: there's a published description of [how new APIs do errors](https://cloud.google.com/apis/design/errors), which includes the canonical [error codes and http mappings](https://github.com/googleapis/googleapis/blob/master/google/rpc/code.proto). This view of errors is slightly newer than BQ, but it's what BQ and other APIs will ultimately converge on.

**Comment by jennybc** [comment]
I am happy to work on this. Re googlesheets4, I've just gotten to the "request processing" stage (vs. request prep, request execution).

I will try to make a PR in the same spirit as https://github.com/r-lib/gh/pull/72/files that exposes everything we know, in a way that suggest how to resolve the problem.

**Comment by jennybc** [comment]
@craigcitro So this source file is the definitive source of Google API error codes? 🤔

https://github.com/googleapis/googleapis/blob/ba1108b3c40c1a674158217f680dac61dd3930f6/google/rpc/code.proto#L26

**Comment by jennybc** [comment]
> This view of errors is slightly newer than BQ, but it's what BQ and other APIs will ultimately converge on.

I'm starting to understand what this means. I suspect that, today, the JSON that comes back for errors has different structure for each API. I'm not sure how much can be shared, other than the tibble below, derived from the [Cloud APIs Errors doc](https://cloud.google.com/apis/design/errors). Sheets v4 appears to send this RPC code and a short description, i.e. we don't gain anything from this table.

But it's possible that one of the other APIs does not and lookup in central object in gargle would be helpful.

``` r
## https://cloud.google.com/apis/design/errors
## https://github.com/googleapis/googleapis/blob/master/google/rpc/error_details.proto
oops <- tibble::tribble(
  ~HTTP,                  ~RPC, ~Description,
    200,                  "OK", "No error.",
    400,    "INVALID_ARGUMENT", "Client specified an invalid argument. Check error message and error details for more information.",
    400, "FAILED_PRECONDITION", "Request can not be executed in the current system state, such as deleting a non-empty directory.",
    400,        "OUT_OF_RANGE", "Client specified an invalid range.",
    401,     "UNAUTHENTICATED", "Request not authenticated due to missing, invalid, or expired OAuth token.",
    403,   "PERMISSION_DENIED", "Client does not have sufficient permission. This can happen because the OAuth token does not have the right scopes, the client doesn't have permission, or the API has not been enabled for the client project.",
    404,           "NOT_FOUND", "A specified resource is not found, or the request is rejected by undisclosed reasons, such as whitelisting.",
    409,             "ABORTED", "Concurrency conflict, such as read-modify-write conflict.",
    409,      "ALREADY_EXISTS", "The resource that a client tried to create already exists.",
    429,  "RESOURCE_EXHAUSTED", "Either out of resource quota or reaching rate limiting. The client should look for google.rpc.QuotaFailure error detail for more information.",
    499,           "CANCELLED", "Request cancelled by the client.",
    500,           "DATA_LOSS", "Unrecoverable data loss or data corruption. The client should report the error to the user.",
    500,             "UNKNOWN", "Unknown server error. Typically a server bug.",
    500,            "INTERNAL", "Internal server error. Typically a server bug.",
    501,     "NOT_IMPLEMENTED", "API method not implemented by the server.",
    503,         "UNAVAILABLE", "Service unavailable. Typically the server is down.",
    504,   "DEADLINE_EXCEEDED", "Request deadline exceeded. This will happen only if the caller sets a deadline that is shorter than the method's default deadline (i.e. requested deadline is not enough for the server to process the request) and the request did not finish within the deadline."
  )
```

**Comment by jennybc** [comment]
Example of response when https://www.googleapis.com/oauth2/v3/tokeninfo endpoint is queried with a state access token:

```
> raw_resp
Response [https://www.googleapis.com/oauth2/v3/tokeninfo]
  Date: 2019-04-22 16:29
  Status: 400
  Content-Type: application/json; charset=UTF-8
  Size: 43 B
{
  "error_description": "Invalid Value"
}
```
