### ISSUE TITLE
GPN-compliant user agent helper

### ISSUE THREAD

**Issue by hadley** [r-lib/gargle#37]
From https://github.com/r-dbi/bigrquery/issues/245

**Comment by jennybc** [comment]
@craigcitro Do you have any knowledge or thoughts there? This was the first time @hadley and I learned about this.

**Comment by craigcitro** [comment]
I have never heard of this before. 😁 Two interesting tidbits:

1. "GPN" doesn't occur in the linked RFC.
2. It sure seems like you're close to following the spec described there?

I'm going to reach out internally to get a little more info.
