### ISSUE TITLE
Dealing with multiple authentication scopes/APIs

### ISSUE THREAD

**Issue by MarkEdmondson1234** [r-lib/gargle#49]
One thing I've coded around in `httr` is dealing with authentication when you have multiple Google login emails/APIs/scopes in one script.  For instance a typical workflow for me is to download from Google Analytics and Search Console, then upload it to Cloud Storage and BigQuery.  

At the beginning there was much confusion from me and users when the scopes/auth failed to match the service, and the dreaded auth errors started up which I'm sure you know are a pain to debug. 

My workaround for this was to ensure explicit authentication each time, and to make sure the options specified in the auth cache file overwrote anything existing in the R environment so that you could write code like:

```r
ga_auth("home.oauth")
...get Google Analytics data...
bq_auth("work.oauth")
...get BigQuery data...
```

...or setup a shared token with mutual scopes:

```r
gar_auth("both.oauth", scopes = c("google_analytics", "big_query"))
...get Google Analytics data...
...get BigQuery data...
```

I realised one day that the `.httr-oauth` file actually contains a list of multiple authentications sometimes, so I think its possible it did support it but I never found an easy way to make it work.  I actually code to make sure that only the first token stored in the `.httr-oauth` is used if there is a list of tokens, as pragmatically debugging one token at a time seemed much easier.

For this reason I also took out the `cache=TRUE or FALSE` option and made it explicitly a filename each time as well, to avoid accidental overwrite of say a `.httr-oauth` file. 

So my question is how is this handled in `gargle`, and can I help at all.

p.s. is there an example of `gargle` being used in a package now or some kind of getting started guide I can use to contribute? Is it only `googlesheets4` for now? Is `gargle` in a state I can start a branch experimenting with it?

**Comment by jennybc** [comment]
> p.s. is there an example of gargle being used in a package now or some kind of getting started guide I can use to contribute? Is it only googlesheets4 for now? Is gargle in a state I can start a branch experimenting with it?

gargle is currently supporting auth in googlesheets4 and the dev version of googledrive. The interface between googledrive and gargle, for auth purposes, live in this file:

https://github.com/tidyverse/googledrive/blob/master/R/drive_auth.R

> So my question is how is this handled in gargle

... where this is having "multiple Google login emails/APIs/scopes". The main response to this in gargle to move the token cache up to the **user** level and stop storing them at the project level. Then when a script or package asks for a token for a specific app, with specific scopes, we can check if something suitable is on hand and, if so, proceed accordingly. So yes the idea is to simultaneously make it easier to reuse tokens across projects and also to use multiple identities within a script.

**Comment by jennybc** [comment]
Current gargle addresses the main points raised here, so I think the task will be to make sure this is well-documented. Yes I felt and have been motivated by many of these exact pain points!

  * "multiple Google login emails/APIs/scopes in one script": Let's say we're using googledrive and googlesheets4 in the same script. `drive_auth_config()` and `sheets_auth_config()` facilitate access to config such as the OAuth app. Only an advanced user would need/care. `drive_auth(email = "???")` and `sheets_auth(email = "???")` allow a regular user to say exactly which Google identity they want to use with each package. Each of those packages maintains its own "auth state" and will not interfere with each other.
    - The current downside, that I would like to address, is they also cannot share a token right now.Not sure if I will accomplish that for v0.1.0, though.
  * Tokens are now cached at the user level, unlike httr's default behaviour of "in the current project".
  * Tokens are now cached in individual files, for easier management.
