### ISSUE TITLE
Enable APIs

### ISSUE THREAD

**Issue by jennybc** [r-lib/gargle#5]
I've gone here:

https://console.developers.google.com

logged in with the necessary Google identify and enabled the Google Drive and Sheets API for the gargle-associated project. I suspect more will need to be enabled in the long run, hence this issue. But I decided to do on an as needed basis. None of this matters until I adopt the new app credentials yet, but ~~I will do that soon~~ that's in #6.

@craigcitro Let me know if there are other APIs I should immediately enable.

**Comment by craigcitro** [comment]
Only other ones I can think of immediately are BQ and GCS -- but IIRC both of those are enabled by default.

**Comment by jennybc** [comment]
OK I will close. We can explicitly enable more if we discover it's necessary.
