### ISSUE TITLE
Packages that could use gargle

### ISSUE THREAD

**Issue by jennybc** [r-lib/gargle#51]
Packages that could conceivably sign on to the gargle bandwagon and perhaps lead to some good de-duplication of developer and user pain:

  * googlesheets4 (successor to googlesheets) <https://github.com/tidyverse/googlesheets4>
  * googledrive <https://github.com/tidyverse/googledrive>
  * gmailr <https://github.com/jimhester/gmailr>
  * bigrquery <https://github.com/r-dbi/bigrquery>
  * ggmap <https://github.com/dkahle/ggmap>

*just a quick "issue as brain dump", others are welcome to chime in*

Before long, I'd like to reach out to others for awareness and invite some discussion.

**Comment by jonthegeek** [comment]
- I assume googleAuthR https://github.com/MarkEdmondson1234/googleAuthR could either use gargle or be absorbed (but @MarkEdmondson1234 might have more to say about that).
- rgoogleslides https://github.com/hairizuanbinnoorazman/rgoogleslides

**Comment by jennybc** [comment]
Yes @markedmondson1234 and I correspond already. He especially has a lot of valuable experience in areas that I do not: GCE, google analytics, and auth w/ Shiny.

**Comment by jonthegeek** [comment]
Excellent! I've done a bit of Auth with Shiny as well (using and expanding on googleAuthR), so I'll gladly help in that area! I've been stalking this project forever, it's time to get involved!

**Comment by MarkEdmondson1234** [comment]
> I assume googleAuthR https://github.com/MarkEdmondson1234/googleAuthR could either use gargle or be absorbed (but @MarkEdmondson1234 might have more to say about that).

I hope to move all the keeping track of user authentication flows to gargle and leave googleAuthR as a "API author" role with utility for API function generator's, Shiny modules and discovery API

**Comment by jennybc** [comment]
This doesn't seem to really be an action item for *me*, since I have no current plans to proactively contact maintainers about switching to gargle.
