### ISSUE TITLE
Publishing gargle to CRAN or other repo

### ISSUE THREAD

**Issue by dlebech** [r-lib/gargle#55]
Hello, I'm using `install_github("r-lib/gargle")` via a Travis-ci job and this fails about 50% of the time because of rate limits from Github. I do not have the same issue with normal CRAN packages, so the question is: Do you have any plans to publish gargle on CRAN or another repo in the near future?

Thank you.

**Comment by jennybc** [comment]
It will go to CRAN soon-ish.

But to solve your immediate problem, you can also use a GitHub personal access token on travis. As an encrypted env var.

**Comment by dlebech** [comment]
Thanks @jennybc , that sounds awesome. I'm on a company Travis account, so it's not so feasible for me to use a personal access token generated by myself, but I will look forward to seeing the repo on CRAN :+1: :tada:

**Comment by dlebech** [comment]
@jennybc I tried setting `GITHUB_PAT` in my Travis build, but then realized that because we're building a Docker image, that environment variable is not available to the build (and as I understand it, it's a security risk to include sensitive environment variables in a Docker build because they can be seen with `docker history`). So the personal access token is actually not even an option for our use case.

Hope to see this on CRAN more-soon-than-soon-ish 🍻 💯

**Comment by jennybc** [comment]
Sent you an email with a bit of advice.
