### ISSUE TITLE
Use for General Authentication?

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/gargle#56]
I'd like to authenticate users within my company (all of whom have Gmail accounts) for uses other than Google APIs specifically (eg, dashboard permissions). I need a way to verify their identity; after that I can deal with verifying the permissions associated with their identity. Would using gargle to verify that the user is who they say they are make sense for this use case, in your opinion?

**Comment by jonthegeek** [comment]
I guess I'd still be using the Google identity api or whatever it's called (the one that returns email address of the current user), so maybe that makes it make more sense?

**Comment by jennybc** [comment]
Maybe @craigcitro would weigh in here? 🙏

It's definitely not the use case I have in mind and what I use gargle for. But perhaps doing what you say actually has very similar requirements to our target use case.

**Comment by craigcitro** [comment]
gargle already supports what I'm used to seeing here -- a user authenticates and includes scope `https://www.googleapis.com/auth/userinfo.email`; that token can then be passed off to the [oauth2 API tokeninfo endpoint](https://www.googleapis.com/discovery/v1/apis/oauth2/v2/rest) as

    https://www.googleapis.com/oauth2/v2/tokeninfo?access_token=<token>

and it'll return a JSON blob including the user's email. This is [`gargle::get_email`](https://github.com/r-lib/gargle/blob/master/R/get-email.R).

A different approach that has advantages but would require new code is to fetch an `id_token` as part of the auth exchange, and then gargle could add support for validating those tokens. These are generally preferred in situations where a token needs to be passed around between different parts of a backend app ([some docs](https://developers.google.com/identity/sign-in/web/backend-auth)).

@jonthegeek does the existing "use `get-email()`" approach work for you?

**Comment by jonthegeek** [comment]
@craigcitro I'm pretty sure get_email() will cover what I need! I'll experiment with it Monday (if not before). Thanks!

**Comment by jonthegeek** [comment]
@craigcitro get_email() isn't exported currently. I'm :::'ing to experiment, but I'm not sure what the proper path is to get the token that get_email needs as an argument. I mean, gargle::token_fetch("https://www.googleapis.com/auth/userinfo.email") does it, but it's re-authing each time I call it, and that doesn't seem quite right.

**Comment by jonthegeek** [comment]
Oooh, passing the email I'm expecting into token_fetch stops it from reauthing, that could fit the workflow...
