### ISSUE TITLE
Auth and Deauth Function Factories

### ISSUE THREAD

**Issue by jonthegeek** [r-lib/gargle#57]
As a package developer, I'd like to easily create auth and deauth functions, so that I can easily implement gargle.

As far as I can tell, only the scopes, error message, and package name for googledrive::drive_auth are unique to googledrive (and nothing is unique to googledrive::drive_deauth). Having factories for these functions would make gargle implementation more straightforward.

I'll submit a PR shortly to close this, but wanted an issue for discussions in case my PR doesn't go as smoothly as I expect.

**Comment by jennybc** [comment]
I have started to record this:

https://gargle.r-lib.org/articles/gargle-auth-in-client-package.html

So take a look there first, then maybe more discussion, before heading to a PR.

**Comment by jennybc** [comment]
Having used gargle (or started to) in googledrive, googlesheets4, and bigrquery, there's a reason that I think client packages need to implement an auth and deauth function. There are small differences that matter in the user-facing function. But I'm trying to layout the pattern and, for example, offer helpers in gargle to make sure that the documentation is standard.

**Comment by jonthegeek** [comment]
Ok, I'll be sure to take a look at all of the implementations before submitting a PR. I think this might be doable, but, if nothing else, I'm teaching myself a bit about function factories (and body() and formals()).

**Comment by jennybc** [comment]
I left my reasoning for closing this on the associate PR #58. Thanks for being a gargle pioneer and please keep the feedback coming.
