### ISSUE TITLE
Should I be using the nominal or actual scopes in the hash?

### ISSUE THREAD

**Issue by jennybc** [r-lib/gargle#60]
Historically, going back to & deriving from httr, the token hash incorporates the *nominal* scope(s), i.e. the requested scope(s).

But from studying my current token collection, I see that this is not the same as *actual* scope(s).

With the email, we take the definitive email from the token itself. Indeed, we must, because there's not necessarily any other way for gargle to know the email.

Should I be doing anything about this? Documenting it well for now.

``` r
options(width = 999)
#knitr::opts_knit$set(width = 999)
```

``` r
devtools::load_all(".")
#> Loading gargle
tokens <- cache_load(gargle_default_oauth_cache_path())

nominal <- purrr::map(tokens, c("params", "scope"))
nominal <- purrr::map_chr(nominal, ~ commapse(base_scope(normalize_scopes(.x))))

actual <- purrr::map(tokens, c("credentials", "scope"))
f <- function(s) {
  if (is.null(s)) return(NA_character_)
  strsplit(s, split = "\\s+")[[1]]
}
actual <- purrr::map(actual, f)
actual <- purrr::map_chr(actual, ~ commapse(base_scope(normalize_scopes(.x))))

tibble::tibble(nominal, actual)
#> # A tibble: 14 x 2
#>    nominal                               actual                                                   
#>    <chr>                                 <chr>                                                    
#>  1 email, ...bigquery, ...cloud-platform ...bigquery, ...cloud-platform, ...userinfo.email, openid
#>  2 email                                 ""                                                       
#>  3 email, mouthwash                      ""                                                       
#>  4 email, ...drive                       ...drive, ...plus.me, ...userinfo.email                  
#>  5 email                                 ...plus.me, ...userinfo.email                            
#>  6 email, ...spreadsheets.readonly       ...plus.me, ...spreadsheets.readonly, ...userinfo.email  
#>  7 email, ...drive                       ...drive, ...userinfo.email, openid                      
#>  8 email, ...drive                       ...drive, ...userinfo.email, openid                      
#>  9 email, ...drive                       ...drive, ...userinfo.email, openid                      
#> 10 email, ...drive                       ...drive, ...userinfo.email, openid                      
#> 11 email, ...drive                       ...drive, ...plus.me, ...userinfo.email                  
#> 12 email, ...drive.readonly              ...drive.readonly, ...plus.me, ...userinfo.email         
#> 13 email, ...bigquery, ...cloud-platform ...bigquery, ...cloud-platform, ...userinfo.email, openid
#> 14 email, ...spreadsheets                ...spreadsheets, ...userinfo.email, openid
```

<sup>Created on 2019-04-16 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>

**Comment by craigcitro** [comment]
From the sidelines: I see two sorts of variation here:

 * scope normalization, eg `email` -> `...userinfo.email`
 * additions, eg adding `openid`/`email`/`plus.me`

The former are harmless (but things should probably be indexed by whatever scopes the Google oauth2 endpoint hands you back, just for sanity).

The latter are more interesting: are they due to R code adding scopes (eg "let's just throw in email") or is the server adding those scopes?

**Comment by jennybc** [comment]
gargle itself add the `email` scope, as a matter of policy.

I'm not doing anything overt that explains the `openid` or `plus.me` scopes, though. I think they're coming from the server.

**Comment by jennybc** [comment]
Many -- but not all -- of these tokens have come about via ongoing development experiments and fiddling. So it's *possible* I caused the `openid` or `plus.me` scopes to happen through something I did. But I have no concrete memory of that.

**Comment by craigcitro** [comment]
With the caveat that "of course there are bound to be situations Craig's never run into", I can't see any obvious harm in indexing based on the requested scopes.

AIUI, the worst case is that you'll be forced to re-auth because (say) a library you use switched from `email` to `...userinfo.email` in an update, which is annoying but hopefully rare. You *could* try handling the "easy" scope normalization, but probably not worth it.

All that said, if some of those examples above are precisely the same email, scopes, **and** client ID, then we might want to think a bit more.

**Comment by jennybc** [comment]
Hashing nominal, i.e. requested scopes, is coming from httr:

https://github.com/r-lib/httr/blob/0dc75595627e9c82ac6950320f4ea8e767bae378/R/oauth-token.r#L105

So empirically it must not cause much harm or we would have suffered by now.

Can you explain this a bit more?

> All that said, if some of those examples above are precisely the same email, scopes, and client ID, then we might want to think a bit more.

I'm in the midst of creating a better way to survey your token collection (that's how I got here), so I am definitely poised to create a view that could shed some light on this.

**Comment by craigcitro** [comment]
> Can you explain this a bit more?

I was trying to guess at your original goals when looking at this. (maybe poorly? 😀 ) 

In particular, let's say we end up with two entries in the cache with distinct nominal scopes but the same actual scopes. The "harm" here is that we've forced a user to do the oauth dance an extra time, which is a bummer, but not a huge deal as long as it's uncommon. (A non-imaginary way this could arise is if we index by nominal scopes, and a library switches from `...userinfo.email` to just `email` in their code: the user will get to do the oauth dance again.)

However, if we end up with two *distinct* cache entries that have the *same* scopes/email/client ID, then that's plausibly a gargle bug, right?

**Comment by jennybc** [comment]
Thanks for elaborating!

I think we have to (continue to) index by nominal scopes. By definition, the scopes that are included there and the way they are expressed are ... the way our users + our wrappers ask for scopes! And, therefore, will lead to the best behaviour re: retrieving tokens from the cache.  The fact that this has stood the test of time with httr is also significant.

This *has* made me wonder if I should refer to the `email` scope by its standard, long name, though.

I'm not sure what to think about the fact that we seem to be getting tokens with the `openid` and/or `plus.me` scopes, but we're not really acknowledging that. I haven't educated myself about what those scopes mean.

**Comment by jennybc** [comment]
To be more clear, if we indexed by the actual scopes, I think we'd get more cases of spurious mismatch between what we have and what user has asked for.

This conversation also makes me think it might be time for a more sophisticated handling of "does this token have the scopes I need?" So we could make this judgment based on *inclusion* instead of *equality*.

**Comment by jennybc** [comment]
> This conversation also makes me think it might be time for a more sophisticated handling of "does this token have the scopes I need?" So we could make this judgment based on inclusion instead of equality.

which is basically #25

**Comment by jennybc** [comment]
Anecdata: all the tokens where the server threw in `plus.me` scope "for free" are from January 2019. None of those tokens include `openid` scope.

No token created in March or April 2019 includes `plus.me`. All of them got `openid` "for free".

*None of my current tokens were created in February 2019.*

**Comment by jennybc** [comment]
Hacky code for this little  investigation, should I ever choose to return to it:

``` r
#+ make-it-wiiiiiiide
options(width = 999)
#knitr::opts_knit$set(width = 999)

#+ real-work
library(tidyverse)
devtools::load_all(".")

tokens <- cache_load(gargle_default_oauth_cache_path())
nms <- names(tokens)
email <- extract_email(nms)

x <- fs::dir_info(gargle_default_oauth_cache_path())
x <- x %>%
  select(path, modification_time) %>% 
  mutate(path = fs::path_file(path))
modification_time <- deframe(x)
modification_time <- modification_time[nms]

app_name <- vapply(tokens, function(t) t$app$appname, "", USE.NAMES = FALSE)
app_key <- vapply(tokens, function(t) t$app$key, "", USE.NAMES = FALSE)
app_key <- substr(app_key, 1, 7)
app_secret <- vapply(tokens, function(t) t$app$secret, "", USE.NAMES = FALSE)
app_secret <- substr(app_secret, 1, 7)

nominal <- purrr::map(tokens, c("params", "scope"))
nominal <- purrr::map_chr(nominal, ~ commapse(base_scope(normalize_scopes(.x))))

actual <- purrr::map(tokens, c("credentials", "scope"))
f <- function(s) {
  if (is.null(s)) return(NA_character_)
  strsplit(s, split = "\\s+")[[1]]
}
actual <- purrr::map(actual, f)
actual <- purrr::map_chr(actual, ~ commapse(base_scope(normalize_scopes(.x))))

x <- tibble::tibble(email, modification_time, app_name, actual, nominal)
readr::write_csv(x, "scope-study.csv")
```

**Comment by jennybc** [comment]
<img width="1241" alt="Screen Shot 2019-04-17 at 12 13 42 PM" src="https://user-images.githubusercontent.com/599454/56314566-44011680-610a-11e9-8c6e-6020fc5588d1.png">

**Comment by jennybc** [comment]
I'm not going to do anything about this at this time.

**Comment by jennybc** [comment]
> This has made me wonder if I should refer to the email scope by its standard, long name, though.

I did choose to do that: https://github.com/r-lib/gargle/commit/f21022da2f3bbdf9f747dd9f4da4f9169859260f
