### ISSUE TITLE
Remove credentials_travis()?

### ISSUE THREAD

**Issue by jennybc** [r-lib/gargle#73]
Here's the current definition of `credentials_travis()`:

https://github.com/r-lib/gargle/blob/master/R/travis-credentials.R

In English: it checks that the `TRAVIS` env var is "true" and then calls `credentials_service_account()`.

From where I sit, it looks like I could delete it.

We certainly don't use it on travis for testing gargle itself or the downstream wrappers I look after. bigrquery, googledrive, etc. use the same approach as gargle, which is to decrypt a service account token, embedded in the shipped package.

@craigcitro What do you think?

**Comment by jennybc** [comment]
I guess if we keep it, we need to put it to work with our travis token flow and it needs to gain some path and decryption smarts along these lines:

``` r
token <- credentials_service_account(
      scopes = "https://www.googleapis.com/auth/userinfo.email",
      path = rawToChar(secret_read("gargle", "gargle-testing.json"))
    )
```

**Comment by jennybc** [comment]
What do you think @Hadley? I guess if we do this right, it could also help in wrappers that use the token management strategy now described here: 

https://gargle.r-lib.org/articles/articles/managing-tokens-securely.html

In which case, it needs a different name.

**Comment by craigcitro** [comment]
I definitely think it's safe to delete -- IIRC it was exploratory-but-unused code, and as you say, there are cleaner ways to do this that don't add to the gargle API surface.

**Comment by hadley** [comment]
Yeah, delete it.
