### ISSUE TITLE
Gargle install fails if fs < 1.3.1 is installed

### ISSUE THREAD

**Issue by ZainRizvi** [r-lib/gargle#88]
My apologies if the below is normal/expected behavior for R packages (I'm pretty new to working with R)

The problem:

What I saw: Installing gargle failed because package fs was out of date
What I expected: Any dependent packages would be automatically updated

I tried manually upgrade the fs package by running  `install.packages("fs")`, but then I hit a new error: `package ‘gargle’ is not available (for R version 3.5.1)` which seems weird since according to CRAN it only relies on R > 3.2 

```

> devtools::install_github("r-lib/gargle")
Downloading GitHub repo r-lib/gargle@master
from URL https://api.github.com/repos/r-lib/gargle/zipball/master
Installing gargle
'/opt/anaconda3/lib/R/bin/R' --no-site-file --no-environ --no-save  \
  --no-restore --quiet CMD INSTALL  \
  '/tmp/RtmpR2Hs6A/devtools29d67f8be03a/r-lib-gargle-3de4f0e'  \
  --library='/opt/anaconda3/lib/R/library' --install-tests

* installing *source* package ‘gargle’ ...
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
Error in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]) :
  namespace ‘fs’ 1.2.5 is being loaded, but >= 1.3.1 is required
ERROR: lazy loading failed for package ‘gargle’
* removing ‘/opt/anaconda3/lib/R/library/gargle’
Installation failed: Command failed (1)

```

**Comment by jennybc** [comment]
I think there's some combination of a weird setup, nonstandard sequence of events, and possibly not reporting everything that happened. This is definitely not a gargle problem, but I'll try to shed some light ...

If you're using conda, you have to fully embrace it. You can't use `install.packages()`, `devtools::install_github()`, etc. It may seem like things are working but you will eventually have headaches. Here's our group's official advice on that:

https://whattheyforgot.org/set-up-an-r-dev-environment.html#what-about-conda

Yes, it is true, that in a normal setup, under normal operations, both `install.packages()` and `devtools::install_github()` should ask you interactively if you'd like to made the necessary upgrades. So your expectation is correct, so something has gone wrong that you got the above result. I hope this helps.

**Comment by ZainRizvi** [comment]
Ah, thanks for the explanation. That was a really useful link

For a fuller context, I was trying to install BigRQuery on GCP AI Platform Notebook's R language notebook.  And yes, AI Platform Notebooks run R using conda.

Any chance of this package and BigRQuery getting posted to conda?

**Comment by jennybc** [comment]
> Any chance of this package and BigRQuery getting posted to conda?

I don't know anything about that. As in, what is the process for packages getting included in that distribution? We definitely have supporters within Google for pushing gargle to release and getting it wired into new releases of bigrquery (coming soon!), so I would think there are people who'd like to make this happen. Good question.

**Comment by ZainRizvi** [comment]
Fingers crossed :)

Thanks for all the hard work!
