### ISSUE TITLE
Problem establishing OAuth cache

### ISSUE THREAD

**Issue by jennybc** [r-lib/gargle#90]
https://github.com/r-dbi/bigrquery/issues/333

*I still need to write this up properly*

**Comment by jennybc** [comment]
@grantmcdermott

I'm having troubling seeing how you travel the code path I see in the bigrquery issue.

Can you show me the result of this on your machine?

``` r
(cache_path <- gargle::gargle_default_oauth_cache_path())
#> Error: 'gargle_default_oauth_cache_path' is not an exported object from 'namespace:gargle'
fs::dir_exists(gargle::gargle_default_oauth_cache_path())
#> Error: 'gargle_default_oauth_cache_path' is not an exported object from 'namespace:gargle'
```

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by grantmcdermott** [comment]
Sure:

``` r
(cache_path <- gargle:::gargle_default_oauth_cache_path())
#> /home/grant/.R/gargle/gargle-oauth
fs::dir_exists(cache_path)
#> /home/grant/.R/gargle/gargle-oauth 
#>                              FALSE
```

<sup>Created on 2019-07-05 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

So I get FALSE. What's odd, though is that I can see it as a GZIP in my file manager.

![gargle](https://user-images.githubusercontent.com/10285037/60746679-00fa5680-9f35-11e9-939b-e6da94096178.png)

**Comment by jennybc** [comment]
Yeah, this is the *real* mystery. What is it even? Can you just delete it and start over from the top? Perhaps something odd got written there during the previous troubles.

**Comment by grantmcdermott** [comment]
Okay, I did that and... now it works! 

(The gargle equivalent of turning it off and then back on again?)

I'm still getting those warning messages about '/home/grant/.config/gcloud' not being a regular file, but I guess those can be silenced in a separate update. 

Thanks again for helping me get to the bottom of this.

**Comment by jennybc** [comment]
Reinstall gargle from Github to silence those warnings. I already fixed that.

**Comment by jennybc** [comment]
I will chalk this up to problems created by the mangled interactive menu about creating a cache, unless someone else reports a problem.

**Comment by grantmcdermott** [comment]
Perfect. Everything works as expected with the latest GH update.

**Comment by adhi-r** [comment]
Just want to add a +1 that a colleague and I came across this issue and we found the same solution - just delete the whole gargle directory and try again.

**Comment by jennybc** [comment]
Yeah sorry @adhi-r. I had several small gargle releases in a row and can't rush into another carelessly. But next week I'll take stock of whether I have other things to add and form a plan w.r.t. another CRAN release. I probably have to do that before releasing a version of googledrive that uses gargle.

**Comment by adhi-r** [comment]
Thanks for all your work @jennybc

**Comment by Dennishi0925** [comment]
Also want to add a +1 
I came across the same issue and found a GZIP file.
After deleting the whole gargle directory, I can establish OAuth cache now.
Thanks @jennybc for your work and @adhi-r for your solution!
