### ISSUE TITLE
Support old .httr-oauth token file locations for  credentials_byo_oauth2() ?

### ISSUE THREAD

**Issue by MarkEdmondson1234** [r-lib/gargle#91]
To aid moving over from old code, would you consider also being able to pass in the file path of an old stylee `.httr-oauth` token to the `credentials_byo_oauth2()` function?  The current behaviour googleAuthR uses is described here https://github.com/r-lib/gargle/issues/49 

It is very almost there at the moment, it needs to only add reading the .rds file of an existing token, and then passing that in to credentials_byo_oauth2(), but perhaps this is a design choice.  At the very least I'll have it in the googleAuthR wrapper of `token_fetch()` to maintain backward compatibility, but thought it may be useful upstream too. 

An example is found here https://github.com/MarkEdmondson1234/googleAuthR/blob/b0e3d621fbc74d4793278e1ccfe62b7fff623c09/R/auth.R#L59

In code it would look like:

```r
library(gargle)
token_fetch(token="/my_old/auth/.httr-oauth")
# or directly via credentials_byo_oauth2(token="/my_old/auth/.httr-oauth")
```

Then as I understand it the token will be saved under the new email regime.

**Comment by jennybc** [comment]
I thought about this in general and declined to do so. Mostly because I think OAuth tokens are (meant to be) perishable and it makes more sense for people to re-auth with gargle than to build something for migration.

> Then as I understand it the token will be saved under the new email regime.

In fact, no, which is part of why I didn't do this. The class (`Token2.0` vs. `Gargle2.0`, which determine this email thing) and the cache path is determined when the token is originally created. We will ingest a token and use it, but there really aren't any facilities for true migration of an OAuth token.

**Comment by MarkEdmondson1234** [comment]
Ok cool, makes sense

**Comment by congthinh** [comment]
> I thought about this in general and declined to do so. Mostly because I think OAuth tokens are (meant to be) perishable and it makes more sense for people to re-auth with gargle than to build something for migration.
> 
> > Then as I understand it the token will be saved under the new email regime.
> 
> In fact, no, which is part of why I didn't do this. The class (`Token2.0` vs. `Gargle2.0`, which determines this email thing) and the cache path is determined when the token is originally created. We will ingest a token and use it, but there really aren't any facilities for true migration of an OAuth token.

Hi Jenny,
My approach with user interaction is as below:
Step 1: I managed to generate .httr_oauth on local machine then uploaded to server
Step 2: Usually, read_sheet requires authentication, I then select a pre-authorised account in .httr-oauth

I am facing trouble with non-interactive env when script running on server via cronjob at step 2.
Any update on this googlesheets4 library that solves this trouble?
Thank you for your time.

**Comment by jennybc** [comment]
googlesheets4 (and all gargle using packages) are, IMO, better at non-interactive auth.

https://gargle.r-lib.org/articles/non-interactive-auth.html
