### ISSUE TITLE
oauth_app_from_json() does not read web based client JSON

### ISSUE THREAD

**Issue by MarkEdmondson1234** [r-lib/gargle#94]
The `oauth_app_from_json()` works great on client JSON for "Other" type clients, but for "Web" type clients it fails.  

The latter is needed for Shiny based auth as it includes the redirect URIs (which will be great to include later on instead of `option(googleAuthR.redirect)`)

The format is largely the same, except it starts with a "web" object and not "installed" e.g.

```json
{"web":{"client_id":"XXX.apps.googleusercontent.com",
"project_id":"blah","auth_uri":"https://accounts.google.com/o/oauth2/auth",
"token_uri":"https://accounts.google.com/o/oauth2/token",
"auth_provider_x509_cert_url":"https://www.googleapis.com/oauth2/v1/certs",
"client_secret":"3nVXXXXXa4",
"redirect_uris":["http://localhost"],
"javascript_origins":["https://www.example.com","http://localhost:1221"]}}
```

Not a pressing issue until Shiny auth is in but a note for future

**Comment by yogat3ch** [comment]
Hi Jenny,
I'm encountering the same issue. 
It looks like a simple fix that will handle multiple app types is just a numerical, name agnostic index on [line 24](https://github.com/r-lib/gargle/blob/5672dabf9379dcecb4f8ada5dc826f415e414382/R/oauth-app.R#L24)
IE
`  info <- jsonlite::fromJSON(path, simplifyVector = FALSE)[["installed"]] ` 
to 
`  info <- jsonlite::fromJSON(path, simplifyVector = FALSE)[[1]] `
