### ISSUE TITLE
secret_read and secreat_write target difference paths

### ISSUE THREAD

**Issue by byapparov** [r-lib/gargle#95]
https://github.com/r-lib/gargle/blob/c74b98019ba66c9398704e1dbee6bed5836cc1a3/R/secret.R#L81

https://github.com/r-lib/gargle/blob/c74b98019ba66c9398704e1dbee6bed5836cc1a3/R/secret.R#L72

this logic points to the `./secret` folder while `secret_write()` targets `./inst/secret/`:

https://github.com/r-lib/gargle/blob/c74b98019ba66c9398704e1dbee6bed5836cc1a3/R/secret.R#L50

Not sure if I am missing something.

**Comment by jennybc** [comment]
A file that lives below `inst/secret/` in package source will live below `secret/` in the installed package. So `fs::path_package()` is the most robust method to point at this file that will work in various contexts.

**Comment by byapparov** [comment]
Ok, I am trying to use it in one of my packages, it is a bit confusing, but hopefully I will manage to get through )

**Comment by byapparov** [comment]
All works fine, thank you.
